name: data_ev
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - pip=23.1.2
  - plotly=5.19.0
  - python-dotenv=1.0.0
  - pandas=2.2.2
  - scipy=1.10.1
  - matplotlib=3.7.2
  - scikit-learn=1.5.1
  - aioboto3=13.4.0
  # boto3 will be installed as a dependency of aioboto3
  - tqdm=4.66.5
  - nbformat=5.10.4
  - msgspec=0.18.6
  - schedule=1.2.2
  - nbstripout=0.8.1
  - statsmodels=0.14.4
  - aiohttp=3.11.11
  - rich=13.5.2
  - pyarrow=19.0.0
  - gspread
  - oauth2client
  - fastapi=0.115.12
  - alembic=1.9.1
  - email-validator=2.2.0
  - httpx=0.23.3
  - orjson=3.8.5
  - inflection=0.5.1
  - python-dateutil=2.8.2
  - python-jose=3.3.0
  - python-multipart>=0.0.18
  - passlib=1.7.4
  - psycopg2-binary=2.9.3
  - asyncpg=0.27.0
  - redis-py=5.2.1
  - minio=7.1.13
  - pillow=9.4.0

  - pip:
      # - git+https://bib-batteries-admin@bitbucket.org/bib-batteries/bib-models.git@main#subdirectory=src
      # - -e .
      - apscheduler==3.10.4
      - aiokafka==0.10.0
      - uuid6==2022.10.25
      - requests==2.30.0
      - fastapi-pagination==0.11.1
      - hypercorn==0.14.3
      - bcrypt==4.0.1
      - pydantic>=1.10.13
      - sqlmodel==0.0.24
      - pydantic-settings==2.2.1

