name: data_ev
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - 
  - pip=23.1.2
  - plotly=5.19.0
  - streamlit=1.32.0
  - python-dotenv=1.0.0
  - pydantic=2.9.2
  - pandas=2.2.2
  - scipy=1.10.1
  - matplotlib=3.7.2
  - scikit-learn=1.5.1
  - boto3=1.26.76
  - requests=2.28.0
  - cbor2=5.6.4
  - tqdm=4.66.5       
  - sqlalchemy=2.0.34w
  - aiohttp=3.10.5
  - nbformat=5.10.4
  - msgspec=0.18.6
  - schedule=1.2.2
  - psycopg2=2.9.9
  - nbstripout=0.8.1
  - statsmodels=0.14.4
  - aiohttp=3.11.11
  
  - pip:
    - git+https://bib-batteries-admin@bitbucket.org/bib-batteries/bib-models.git@main#subdirectory=src
    - -e .
    - apscheduler==3.10.4
