name: data_ev
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - pip=23.1.2
  - plotly=5.19.0
  - streamlit=1.32.0
  - python-dotenv=1.0.0
  - pydantic=1.10.7
  - pandas=2.2.2
  - scipy=1.10.1
  - s3fs=2023.6.0
  - matplotlib = 3.7.2
  - scikit-learn=1.5.1
  - boto3=1.26.76
  - cbor2=5.6.4
  - pip:
    - -e .

