# https://taskfile.dev

version: '3'

vars:
  RDB_INSTANCE_ID: 196b3cc5-8de2-4a4c-bcfa-57f06b2b8364
  RDB_DATABASE_NAME: rdb
  LOCAL_DB_HOST: localhost
  LOCAL_DB_PORT: 55432
  LOCAL_DB_NAME: evalue
  LOCAL_DB_USER: evalue
  LOCAL_DB_PASSWORD: evalue

tasks:
  dagster:redeploy:
    cmds:
      - docker compose build dagster-user-deployment --push
      - kubectl --context $BIB_KAPSULE_PROD rollout restart deployment -n dagster user-code-dagster-user-deployments-bib-code
      - kubectl --context $BIB_KAPSULE_PROD rollout status deployment -n dagster user-code-dagster-user-deployments-bib-code
    silent: true

  evalue:back:build-deploy:
    cmds:
      - docker compose build external_api --push
      - kubectl --context $BIB_KAPSULE_PROD rollout restart deployment -n evalue external-api
      - kubectl --context $BIB_KAPSULE_PROD rollout status deployment -n evalue external-api
    silent: true

  db:production:backup:
    desc: Create a backup of the production Scaleway RDB
    cmds:
      - |
        BACKUP_ID=$(scw rdb backup create instance-id={{.RDB_INSTANCE_ID}} name="rdb-$(whoami)-$(date +%s)" database-name={{.RDB_DATABASE_NAME}} expires-at=$(TZ=UTC-24 date +%Y-%m-%dT%H:%M:%SZ) --output json | jq -r '.id')
        scw rdb backup wait $BACKUP_ID
        scw rdb backup export $BACKUP_ID
        echo "To restore this backup, run: task db:restore"
        echo "🚨 This is only usable for now because the DB is small (~10MB). When reaching a few GB, we'll need to think about something else."
    silent: true

  db:local:restore:
    desc: Restore the latest Scaleway RDB backup to local PostgreSQL
    cmds:
      - |
        echo "Finding latest backup for instance {{.RDB_INSTANCE_ID}}..."
        BACKUP_ID=$(scw rdb backup list instance-id={{.RDB_INSTANCE_ID}} --output json | jq -r 'sort_by(.created_at) | reverse | .[0].ID')
        if [ -z "$BACKUP_ID" ] || [ "$BACKUP_ID" = "null" ]; then
          echo "Error: No backups found for instance {{.RDB_INSTANCE_ID}}"
          exit 1
        fi
        DOWNLOAD_URL=$(scw rdb backup get $BACKUP_ID --output json | jq -r '.download_url')
        curl -L -o /tmp/rdb_backup.custom "$DOWNLOAD_URL"
        docker compose down postgres -v
        docker compose up -d postgres
        sleep 3
        docker compose cp /tmp/rdb_backup.custom postgres:/tmp/rdb_backup.custom
        docker compose exec -T postgres bash -c "pg_restore --list /tmp/rdb_backup.custom | grep -v pgaudit > /tmp/rdb_restore.list"
        docker compose exec -T postgres pg_restore -U {{.LOCAL_DB_USER}} -d {{.LOCAL_DB_NAME}} --no-owner --no-acl -L /tmp/rdb_restore.list /tmp/rdb_backup.custom
        rm /tmp/rdb_backup.custom
    silent: true

  db:local:backup-and-restore:
    desc: Create a backup and restore it to local database (all-in-one)
    cmds:
      - task: db:production:backup
      - sleep 5
      - task: db:local:restore
    silent: false
