import os
from dotenv import load_dotenv

load_dotenv()

# API Configuration
BMW_AUTH_URL = os.getenv('BMW_AUTH_URL')
BMW_BASE_URL = os.getenv('BMW_BASE_URL')
BMW_CLIENT_ID = os.getenv('BMW_CLIENT_ID')
BMW_FLEET_ID = os.getenv('BMW_FLEET_ID')
BMW_CLIENT_USERNAME = os.getenv('BMW_CLIENT_USERNAME')
BMW_CLIENT_PASSWORD = os.getenv('BMW_CLIENT_PASSWORD')

HM_BASE_URL = os.getenv('HM_BASE_URL')
HM_CLIENT_ID = os.getenv('HM_CLIENT_ID')
HM_CLIENT_SECRET = os.getenv('HM_CLIENT_SECRET')

STELLANTIS_BASE_URL = os.getenv('MS_BASE_URL')
STELLANTIS_EMAIL = os.getenv('MS_EMAIL')
STELLANTIS_PASSWORD = os.getenv('MS_PASSWORD')
STELLANTIS_FLEET_ID = os.getenv('MS_FLEET_ID')
STELLANTIS_COMPANY_ID = os.getenv('MS_COMPANY')

SLACK_TOKEN = os.getenv('SLACK_TOKEN')
SLACK_CHANNEL_ID = os.getenv('SLACK_CHANNEL_ID')
SPREADSHEET_ID = os.getenv('SPREADSHEET_ID')
TESLA_BASE_URL = os.getenv('TESLA_BASE_URL')

RENAULT_KID = os.getenv('RENAULT_KID')
RENAULT_AUD = os.getenv('RENAULT_AUD')
RENAULT_CLIENT = os.getenv('RENAULT_CLIENT')
RENAULT_SCOPE = os.getenv('RENAULT_SCOPE')
RENAULT_PWD = os.getenv('RENAULT_PWD')
