# For now leave BMW in capital as bmw is used for the data provided by high mobility.
BMW_RAW_TSS_KEY = "raw_ts/BMW/raw_tss.parquet"
BMW_RAW_TSS_KEY_WITHOUT_UNITS = "raw_ts/BMW/raw_tss_without_units.parquet"

VARIABLES_THAT_WE_ASKED_FOR = [
    {'key_type': 'VEHICLE', 'key_name': 'battery_voltage', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_ac_ampere', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_ac_voltage', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'soc_target_charging_time_forecast', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'basic_charging_modes', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'last_trip_electric_energy_consumption_comfort', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'avg_electric_range_consumption', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'steering', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'eco_drive_mode_mileage_yesterday', 'unit': 'float', 'update_interval': 'DAILY'},
    {'key_type': 'VEHICLE', 'key_name': 'weighted_avg_energy_consumption_yesterday', 'unit': 'float', 'update_interval': 'DAILY'},
    {'key_type': 'VEHICLE', 'key_name': 'electric_share_yesterday', 'unit': 'float', 'update_interval': 'DAILY'},
    {'key_type': 'VEHICLE', 'key_name': 'soc_hv_header', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'model', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_planning_mode', 'unit': 'boolean', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_plug_connected_dc', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_plug_connected', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_status', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charging_method', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charge_plug_event_id', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'charge_plug_locked', 'unit': 'boolean', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'soc_customer_target_range', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'soc_customer_target', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'brand', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'last_trip_ratio_electric_driven_distance', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'basic_construction_date', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'last_trip_SOC_segment_end', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'drive_in_inspection_due_date', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'power', 'unit': 'integer', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'last_trip_electric_recuperation_overall', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'speed_avg', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'electric_mileage_yesterday', 'unit': 'float', 'update_interval': 'DAILY'},
    {'key_type': 'VEHICLE', 'key_name': 'travelled_distance_yesterday', 'unit': 'float', 'update_interval': 'DAILY'},
    {'key_type': 'VEHICLE', 'key_name': 'remaining_mileage', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'capacity', 'unit': 'float', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'mileage', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'data_quality', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'basic_model_range', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'teleservice_status', 'unit': 'string', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'kombi_remaining_electric_range', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'basic_propulsion_type', 'unit': 'string', 'update_interval': 'ONCE'},
    {'key_type': 'VEHICLE', 'key_name': 'coolant_temperature', 'unit': 'integer', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'average_mileage_per_week', 'unit': 'float', 'update_interval': 'CURRENT'},
    {'key_type': 'VEHICLE', 'key_name': 'basic_drive_train', 'unit': 'string', 'update_interval': 'ONCE'}
]

