VIN_DICTIONARY = {
    "first_to_third": {
        "5YJ": "USA 3/S",
        "7G2": "USA SEMI",
        "7SA": "USA X/Y",
        "SFZ": "UK ROADSTER",
        "LRW": "CHINA",
        "XP7": "GERMANY",
    },
    "fourth": {
        "3": "Tesla Model 3",
        "Y": "Tesla Model Y",
        "S": "Tesla Modèle S",
        "X": "Tesla Modèle X",
        "R": "Tesla Roadster",
        "T": "Tesla Semi",
        "C": "Tesla Cybertruck",
    },
    "fifth": {
        "A": "5 portes, conduite à gauche, Hayon (Model S) / Berline (Model 3)",
        "B": "5 portes, conduite à droite, hayon (Model S) / Berline (Model 3) / Cabine (Semi)",
        "C": "5 portes, conduite à gauche, SUV",
        "D": "5 portes, conduite à droite, SUV",
        "E": "Conduite à gauche, 4 portes, Berline (Model 3) / 3 portes, Cabriolet (Roadster)",
        "G": "5 portes, conduite à gauche, SUV-Crossover",
        "H": "5 portes, conduite à droite, SUV-Crossover",
    },
    "sixth": {
        "1": "Ceintures de sécurité (2 à l'avant, 3 à l'arrière), airbags frontaux, airbags genoux (à l'avant), airbags latéraux, PODS",
        "3": "Ceintures de sécurité (2 à l'avant, 2 à l'arrière), airbags frontaux, airbags genoux (à l'avant), airbags latéraux",
        "4": "Ceintures de sécurité (2 à l'avant, 2 à l'arrière), airbags frontaux, airbags genoux (à l'avant), airbags latéraux",
        "5": "Ceintures de sécurité (2 avant, 2 arrière), airbags frontaux, airbags latéraux",
        "6": "Ceintures de sécurité (2 avant, 3 arrière), airbags frontaux, airbags latéraux",
        "7": "Ceintures de sécurité (2 avant, 3 arrière), airbags frontaux, airbags latéraux, capot actif",
        "8": "Ceintures de sécurité (2 avant, 2 arrière), airbags frontaux, airbags latéraux, capot actif",
        "A": "Ceintures de sécurité (2 à l'avant, 3 en deuxième rangée, 2 en troisième rangée), airbags frontaux, airbags genoux (à l'avant), airbags latéraux, PODS",
        "B": "Ceintures de sécurité (2 avant, 2 deuxième rangée, 2 troisième rangée), airbags frontaux, airbags genoux (avant), airbags latéraux, PODS",
        "C": "Ceintures de sécurité (2 avant, 2 deuxième rangée, 2 troisième rangée), airbags frontaux, airbags latéraux, PODS",
        "D": "Ceintures de sécurité (2 avant, 3 arrière), airbags frontaux, airbags genoux (avant), airbags latéraux, PODS",
    },
    "seventh": {
        "A": "Chargeur avec puissance de charge de 10 kW",
        "B": "Chargeur avec puissance de charge de 20 kW",
        "C": "Chargeur avec puissance de charge de 10 kW et chargeur rapide DC",
        "D": "Chargeur avec puissance de charge de 20 kW et chargeur rapide DC",
        "E": "Batterie NMC/NCA",
        "F": "Batterie LFP",
        "H": "Batterie NMC de grande capacité (85 kWh)",
        "S": "Batterie NMC de capacité standard (60 kWh)",
        "V": "Batterie NMC à très haute capacité (90 kWh)",
    },
    "eighth": {
        "1": "Un moteur à induction standard à courant alternatif, triphasé",
        "2": "Deux moteurs à induction standard à courant alternatif, triphasé",
        "3": "Un moteur à induction à courant alternatif de performance, triphasé",
        "4": "Deux moteurs à induction à courant alternatif de performance, triphasés",
        "5": "Deux moteurs (Facelift Model S/X)",
        "6": "Trois moteurs (Model S/X Plaid)",
        "A": 'Un moteur standard ou performance de type "Wire Windings"',
        "B": 'Deux moteurs standard de type "Wire Windings" (3#DB, Model 3 ou Semi)',
        "C": 'Deux moteurs Performance de type "Wire Windings" avec batterie de 82 kWh',
        "D": 'Un moteur standard ou performance de type "Wire Windings"',
        "E": 'Deux moteurs standard de type "Wire Windings" (Y#DB, Model Y)',
        "F": 'Deux moteurs Performance de type "Wire Windings" (Y#DP)',
        "G": "moteur non spécifié, batterie 51-60 kWh",
        "J": 'Un moteur standard/performance de type "Hairpin Windings"',
        "K": 'Deux moteurs standard de type "Hairpin Windings"',
        "L": 'Deux moteurs Performance de type "Hairpin Windings"',
        "N": "Un moteur standard, batterie 81-90 kWh",
        "P": "Un moteur Performance, batterie 81-90 kWh",
        "R": 'Un moteur standard de type "Wire Windings" (Y#RB, 3#RB)',
        "S": 'Un moteur standard de type "Hairpin Windings" (Y#RB, 3#RB)',
        "T": "Deux moteurs de performance",
    },
    "tenth": {
        "6": 2006,
        "7": 2007,
        "8": 2008,
        "9": 2009,
        "A": 2010,
        "B": 2011,
        "C": 2012,
        "D": 2013,
        "E": 2014,
        "F": 2015,
        "G": 2016,
        "H": 2017,
        "J": 2018,
        "K": 2019,
        "L": 2020,
        "M": 2021,
        "N": 2022,
        "P": 2023,
        "R": 2024,
        "S": 2025,
    },
    "eleventh": {
        "1": "Californie, Menlo Park",
        "3": "Grande-Bretagne, Hethel (Roadster)",
        "A": "Texas, Austin",
        "B": "Allemagne, Berlin/Grünheide",
        "C": "Chine, Shanghai",
        "F": "Californie, Fremont",
        "G": "Allemagne, Berlin/Grünheide",
        "N": "Nevada, Reno",
        "P": "Californie, Palo Alto",
        "R": "Développement / Recherche",
    },
    "twelfth": {
        "A": "Prototype Stade Alpha",
        "B": "Prototype Stade Bêta",
        "E": "Prototype d'évaluation (Roadster)",
        "F": "Série Founder (Roadster numéro 1 à 1000)",
        "M": "Prototype roulant (Roadster)",
        "P": "Véhicule de production (seulement les 100 000 premières Model S)",
        "R": "Candidat à la sortie",
        "S": "Série Signature (premiers 1000 Model S/X)",
        "V": "Prototype de validation (Roadster)",
    },
}

QUERY = """
    WITH vin_parts AS (
        SELECT
            v.vin,
            CAST(b.net_capacity AS VARCHAR) AS net_capacity,
            LEFT(v.vin, 11) AS discriminative_vin,
            LEFT(v.vin, 3) as factory,
            RIGHT(LEFT(v.vin, 4), 1) AS model,
            RIGHT(LEFT(v.vin, 5), 1) AS carrosserie_volant,
            RIGHT(LEFT(v.vin, 6), 1) AS securite,
            RIGHT(LEFT(v.vin, 7), 1) AS propulsion,
            RIGHT(LEFT(v.vin, 8), 1) AS motorisation,
            RIGHT(LEFT(v.vin, 9), 1) AS ctrl,
            RIGHT(LEFT(v.vin, 10), 1) AS year,
            RIGHT(LEFT(v.vin, 11), 1) AS loc_factory,
            vm.model_name ,
            vm.type,
            vm.version,
            vm.type || '|' || vm.version || '|' || b.net_capacity AS type_version_capa
        FROM vehicle v
        LEFT JOIN vehicle_model vm
            ON v.vehicle_model_id = vm.id
        LEFT JOIN oem o
            ON o.id = vm.oem_id
        LEFT JOIN battery b
            ON b.id = vm.battery_id
        WHERE o.oem_name = 'tesla'
        AND vm.type is not null
    )
    SELECT
        discriminative_vin,
        STRING_AGG(DISTINCT type, ', ' ORDER BY type) AS type,
        STRING_AGG(DISTINCT version, ', ' ORDER BY version) AS version,
        STRING_AGG(distinct type_version_capa, ';') as type_version_capa,
        STRING_AGG(DISTINCT net_capacity, ', ') AS net_capacities
    FROM vin_parts
    GROUP BY 1;
"""

QUERY_PARTIAL = """
    WITH vin_parts AS (
        SELECT
            v.vin,
            CAST(b.net_capacity AS VARCHAR) AS net_capacity,
            CONCAT(right(LEFT(v.vin, 5), 2), right(LEFT(v.vin, 10), 4)) AS discriminative_vin,
            LEFT(v.vin, 3) as factory,
            RIGHT(LEFT(v.vin, 4), 1) AS model,
            RIGHT(LEFT(v.vin, 5), 1) AS carrosserie_volant,
            RIGHT(LEFT(v.vin, 6), 1) AS securite,
            RIGHT(LEFT(v.vin, 7), 1) AS propulsion,
            RIGHT(LEFT(v.vin, 8), 1) AS motorisation,
            RIGHT(LEFT(v.vin, 9), 1) AS ctrl,
            RIGHT(LEFT(v.vin, 10), 1) AS year,
            RIGHT(LEFT(v.vin, 11), 1) AS loc_factory,
            vm.model_name ,
            vm.type,
            vm.version,
            vm.type || '|' || vm.version || '|' || b.net_capacity AS type_version_capa
        FROM vehicle v
        LEFT JOIN vehicle_model vm
            ON v.vehicle_model_id = vm.id
        LEFT JOIN oem o
            ON o.id = vm.oem_id
        LEFT JOIN battery b
            ON b.id = vm.battery_id
        WHERE o.oem_name = 'tesla'
        AND vm.type is not null
    )
    SELECT
        discriminative_vin,
        STRING_AGG(DISTINCT type, ', ' ORDER BY type) AS type,
        STRING_AGG(DISTINCT version, ', ' ORDER BY version) AS version,
        STRING_AGG(distinct type_version_capa, ';') as type_version_capa,
        STRING_AGG(DISTINCT net_capacity, ', ') AS net_capacities
    FROM vin_parts
    GROUP BY 1;
"""

WMI_TO_OEM = {
    "AAA": "Audi",
    "AAK": "FAW",
    "AAM": "MAN",
    "AAP": "SAPVIN",
    "AAV": "Volkswagen",
    "AAW": "Challenger Trailer",
    "AA9": "Tec",
    "ABJ": "Mitsubishi",
    "ABM": "BMW",
    "ACV": "Isuzu",
    "AC5": "Hyundai",
    "AC9": "Beamish",
    "ADB": "Mercedes-Benz",
    "ADD": "UD Trucks",
    "ADM": "General Motors",
    "ADN": "Nissan",
    "ADR": "Renault",
    "ADX": "Tata",
    "AE9": "Backdraft Racing",
    "AFA": "Ford",
    "AFB": "Mazda",
    "AFD": "BAIC",
    "AFZ": "Fiat",
    "AHH": "Hino",
    "AHM": "Honda",
    "AHT": "Toyota",
    "BF9": "KIBO",
    "BUK": "Kiira",
    "BR1": "Mercedes-Benz",
    "BRY": "Fiat",
    "CA3": "MCV",
    "DDY": "Geyushi",
    "DF9": "Laraki",
    "EAA": "Aurus",
    "EAN": "Evolute",
    "EAU": "EVM",
    "EBE": "Sollers",
    "EBZ": "Nizhekotrans",
    "ECE": "XCITE",
    "ECW": "Alfa",
    "HA0": "Sundiro",
    "HA6": "Niu",
    "HA7": "Qingqi",
    "HES": "smart",
    "HGL": "Farizon",
    "HGX": "Wuling",
    "HHZ": "Huazi",
    "HJR": "Jetour",
    "HJZ": "Juzhen Chengshi",
    "HJ4": "BAW",
    "HL4": "Moto Morini",
    "HLX": "Li Auto",
    "HRV": "Henrey",
    "HVW": "Volkswagen",
    "HWM": "WM Motor",
    "HZ2": "Zhilong",
    "H0D": "Qianxin",
    "H0G": "Wisdom",
    "JAA": "Isuzu",
    "JAB": "Isuzu",
    "JAC": "Isuzu",
    "JAE": "Acura",
    "JAL": "Isuzu",
    "JAM": "Isuzu",
    "JA3": "Mitsubishi",
    "JA4": "Mitsubishi",
    "JA7": "Mitsubishi",
    "JB3": "Dodge",
    "JB4": "Dodge",
    "JB7": "Dodge",
    "JC0": "Ford",
    "JC1": "Fiat",
    "JC2": "Ford",
    "JDA": "Daihatsu",
    "JD1": "Daihatsu",
    "JD2": "Daihatsu",
    "JD4": "Daihatsu",
    "JE3": "Mitsubishi",
    "JE4": "Mitsubishi",
    "JF1": "Subaru",
    "JF2": "Subaru",
    "JF3": "Subaru",
    "JF4": "Saab",
    "JG1": "Suzuki",
    "JG2": "Suzuki",
    "JG7": "Suzuki",
    "JGC": "Suzuki",
    "JGT": "Suzuki",
    "JHA": "Hino",
    "JHB": "Hino",
    "JHD": "Hino",
    "JHF": "Hino",
    "JH1": "Honda",
    "JHM": "Honda",
    "JHL": "Honda",
    "JJ3": "Chrysler",
    "JKA": "Kawasaki",
    "JKB": "Kawasaki",
    "JKM": "Mitsuoka",
    "JKS": "Kawasaki",
    "JK8": "Kawasaki",
    "JLB": "Mitsubishi",
    "JLF": "Mitsubishi",
    "JLS": "Sterling",
    "JL5": "Mitsubishi",
    "JL6": "Mitsubishi",
    "JL7": "Mitsubishi",
    "JMA": "Mitsubishi",
    "JMB": "Mitsubishi",
    "JMF": "Mitsubishi",
    "JMP": "Mitsubishi",
    "JMR": "Mitsubishi",
    "JMY": "Mitsubishi",
    "JMZ": "Mazda",
    "JM0": "Mazda",
    "JM1": "Mazda",
    "JM2": "Mazda",
    "JM3": "Mazda",
    "JM4": "Mazda",
    "JM6": "Mazda",
    "JM7": "Mazda",
    "JNA": "Nissan",
    "JNC": "Nissan",
    "JNE": "Nissan",
    "JNK": "Infiniti",
    "JNR": "Infiniti",
    "JNX": "Infiniti",
    "JN1": "Nissan",
    "JN3": "Nissan",
    "JN6": "Nissan",
    "JN8": "Nissan",
    "JPC": "Nissan",
    "JP3": "Mitsubishi",
    "JP4": "Mitsubishi",
    "JP7": "Mitsubishi",
    "JR2": "Isuzu",
    "JSA": "Suzuki",
    "JSK": "Kawasaki",
    "JSL": "Kawasaki",
    "JST": "Suzuki",
    "JS1": "Suzuki",
    "JS2": "Suzuki",
    "JS3": "Suzuki",
    "JS4": "Suzuki",
    "JTB": "Toyota",
    "JTD": "Toyota",
    "JTE": "Toyota",
    "JTF": "Toyota",
    "JTG": "Toyota",
    "JTH": "Lexus",
    "JTJ": "Lexus",
    "JTK": "Toyota",
    "JTL": "Toyota",
    "JTM": "Toyota",
    "JTN": "Toyota",
    "JTP": "Toyota",
    "JT1": "Toyota",
    "JT2": "Toyota",
    "JT3": "Toyota",
    "JT4": "Toyota",
    "JT5": "Toyota",
    "JT6": "Lexus",
    "JT7": "Toyota",
    "JT8": "Lexus",
    "JW6": "Mitsubishi",
    "JYA": "Yamaha",
    "JYE": "Yamaha",
    "JY3": "Yamaha",
    "JY4": "Yamaha",
    "J81": "Isuzu",
    "J87": "Isuzu",
    "J8B": "Isuzu",
    "J8C": "Isuzu",
    "J8D": "Isuzu",
    "J8T": "Isuzu",
    "J8Z": "Isuzu",
    "KF3": "Merkavim",
    "KF6": "Automotive",
    "KF9": "Tomcar",
    "KG9/002": "Charash Ashdod",
    "KG9/004": "H. Klein",
    "KG9/007": "Agam Trailers",
    "KG9/009": "Merkavey Noa",
    "KG9/010": "Weingold Trailers",
    "KG9/011": "Netzer Sereni",
    "KG9/015": "Merkaz Hagrorim",
    "KG9/035": "BEL Technologies",
    "KG9/091": "Jansteel",
    "KG9/101": "Bassamco",
    "KG9/104": "Global Handasa",
    "KL": "Daewoo",
    "KLA": "Daewoo",
    "KLP": "CT",
    "KLT": "Daewoo",
    "KLU": "Daewoo",
    "KLY": "Daewoo",
    "KL1": "Daewoo",
    "KL2": "Daewoo",
    "KL3": "Daewoo",
    "KL4": "GM",
    "KL5": "Daewoo",
    "KL6": "Daewoo",
    "KL7": "Daewoo",
    "KL8": "Daewoo",
    "KM": "Hyundai",
    "KMC": "Hyundai",
    "KME": "Hyundai",
    "KMF": "Hyundai",
    "KMH": "Hyundai",
    "KMJ": "Hyundai",
    "KMT": "Genesis",
    "KMU": "Genesis",
    "KMX": "Hyundai",
    "KMY": "Daelim",
    "KM1": "Hyosung",
    "KM4": "Hyosung",
    "KM8": "Hyundai",
    "KNA": "Kia",
    "KNC": "Kia",
    "KND": "Kia",
    "KNE": "Kia",
    "KNF": "Kia",
    "KNG": "Kia",
    "KNJ": "Kia",
    "KNM": "Renault",
    "KN1": "Asia",
    "KN2": "Asia",
    "KPA": "SsangYong",
    "KPB": "SsangYong",
    "KPD": "SsangYong",
    "KPH": "Mitsubishi",
    "KPT": "SsangYong",
    "LAA": "Jialing",
    "LAE": "Qingqi",
    "LAL": "Honda",
    "LAN": "Yamasaki",
    "LAP": "Jianshe",
    "LAT": "Northern Ek Chor",
    "LA6": "King Long",
    "LA7": "Radar Auto",
    "LA8": "Ankai",
    "LA9/AYS": "Bus",
    "LA9/BFC": "Neoplan",
    "LA9/FBC": "Bus",
    "LA9/HFF": "Vehicle",
    "LA9/JXK": "Bonluck",
    "LA9/LC0": "BYD",
    "LA9/LFJ": "Xinlongma",
    "LA9/LM6": "Shineray",
    "LBB": "Qianjiang",
    "LBE": "Hyundai",
    "LBM": "Piaggio",
    "LBP": "Yamaha",
    "LBV": "BMW",
    "LBX": "Kinroad Xintian",
    "LBZ": "Shuchi",
    "LB1": "Benz",
    "LB2": "Geely",
    "LB3": "Geely",
    "LB4": "Yinxiang",
    "LB5": "Foshan Fosti",
    "LB7": "Tibet New Summit",
    "LCE": "Chunfeng",
    "LCR": "Gonow",
    "LC0": "BYD",
    "LC2": "Kwang Yang",
    "LC6": "Suzuki",
    "LDB": "Dadi Auto",
    "LDC": "Dongfeng",
    "LDD": "Huanghai",
    "LDF": "Dezhou Fulu",
    "LDK": "FAW",
    "LDN": "Soueast",
    "LDP": "Dongfeng",
    "LDY": "Zhongtong",
    "LD3": "Tayo",
    "LD5": "Benzhou Vehicle",
    "LD9/L3A": "SiTech",
    "LEC": "Qingyuan",
    "LEF": "Jiangling",
    "LEH": "Riya",
    "LET": "Isuzu",
    "LEW": "Dongfeng",
    "LE4": "Jeep",
    "LE8": "Panyu Hua'Nan",
    "LFB": "Mazda",
    "LFF": "Taizhou Wangye",
    "LFG": "Chuanl",
    "LFJ": "Motors",
    "LFM": "Toyota",
    "LFN": "FAW",
    "LFP": "Mazda",
    "LFT": "FAW",
    "LFU": "Lifeng",
    "LFV": "Volkswagen",
    "LFW": "FAW",
    "LFX": "Sany Heavy",
    "LFY": "Changshu Light",
    "LFZ": "Leapmotor",
    "LF3": "Lifan",
    "LGA": "Dongfeng",
    "LGB": "Dongfeng",
    "LGC": "Dongfeng",
    "LGF": "Dongfeng",
    "LGG": "Dongfeng",
    "LGJ": "Dongfeng",
    "LGL": "Daewoo",
    "LGV": "Guoji Nanlian",
    "LGW": "Great Wall Motor",
    "LGX": "BYD",
    "LGZ": "Denway",
    "LG6": "Dayun",
    "LHA": "Shuanghuan Auto",
    "LHB": "Automotive",
    "LHG": "Honda",
    "LHJ": "Bashan",
    "LHM": "Dongfeng",
    "LHW": "CRRC Electric",
    "LH0": "WM Motor",
    "LH1": "FAW",
    "LJC": "Jincheng",
    "LJD": "Kia",
    "LJM": "Sunlong",
    "LJN": "Nissan",
    "LJR": "CIMC",
    "LJS": "Coach",
    "LJU": "Lotus Technology",
    "LJV": "Chengdu Wangpai",
    "LJW": "Landwind",
    "LJX": "Ford",
    "LJ1": "Nio",
    "LJ4": "Jmstar",
    "LJ5": "Cixi Kingring",
    "LJ8": "Zotye Auto",
    "LKC": "BAIC",
    "LKG": "Lotus",
    "LKH": "Motor",
    "LKL": "Bus",
    "LKT": "Yunnan Lifan Junma",
    "LK2": "JAC",
    "LK6": "SAIC",
    "LK8": "Yule",
    "LLC": "Motor",
    "LLJ": "Xinling",
    "LLN": "Qoros",
    "LLP": "Jiajue",
    "LLU": "Dongfeng",
    "LLV": "Lifan",
    "LLX": "Yudo Auto",
    "LL0": "Sanmen Yongfu",
    "LL2": "WM Motor",
    "LL3": "Golden Dragon",
    "LL6": "Mitsubishi",
    "LL8": "Yamaha",
    "LMC": "Suzuki",
    "LME": "Skyworth",
    "LMF": "Zhongyu",
    "LMG": "GAC",
    "LMH": "Guowei",
    "LMP": "Geely",
    "LMV": "XPeng",
    "LMW": "GAC",
    "LMX": "Forthing",
    "LM0": "Holdings",
    "LM6": "SWM",
    "LM8": "Seres",
    "LNA": "GAC",
    "LNB": "BAIC",
    "LND": "JMEV",
    "LNE": "CRRC Electric",
    "LNP": "Fiat",
    "LNN": "Jaecoo",
    "LNV": "Naveco",
    "LNX": "Dongfeng",
    "LNY": "Yuejin",
    "LPA": "Changan",
    "LPE": "BYD",
    "LPS": "Polestar",
    "LP6": "Panyu Haojian",
    "LRB": "General Motors",
    "LRD": "Daimler",
    "LRE": "General Motors",
    "LRP": "Rato",
    "LRW": "Tesla",
    "LR4": "Yadi",
    "LR6": "Dayun",
    "LSC": "Changan",
    "LSF": "SAIC",
    "LSG": "General Motors",
    "LSH": "SAIC",
    "LSJ": "SAIC",
    "LSK": "SAIC",
    "LSV": "Volkswagen",
    "LSY": "Brilliance",
    "LS3": "Hejia New Energy",
    "LS4": "Changan",
    "LS5": "Changan",
    "LS6": "Changan",
    "LS7": "JMC",
    "LS8": "Henan Shaolin Auto",
    "LTA": "ZX Auto",
    "LTN": "Chrysler",
    "LTP": "NEVS",
    "LTV": "Toyota",
    "LTW": "Dianka",
    "LT1": "Yangzhou Tonghua",
    "LUC": "Honda",
    "LUD": "Dongfeng",
    "LUG": "Qiantu",
    "LUJ": "Shanqi Tianying",
    "LUR": "Chery",
    "LUX": "Dongfeng",
    "LUZ": "Hozon Auto",
    "LVA": "Foton",
    "LVB": "Foton",
    "LVC": "Foton",
    "LVF": "Suzuki",
    "LVG": "Toyota",
    "LVH": "Dongfeng",
    "LVM": "Chery",
    "LVP": "Dongfeng",
    "LVR": "Changan",
    "LVS": "Changan",
    "LVT": "Exeed",
    "LVU": "Jetour",
    "LVV": "Jaecoo",
    "LVX": "Landwind",
    "LVY": "Volvo",
    "LVZ": "Dongfeng",
    "LV3": "Hengchi",
    "LV7": "Qingqi",
    "LWB": "Honda",
    "LWE": "Yangtse",
    "LWG": "Huansong",
    "LWL": "Isuzu",
    "LWM": "Wonjan",
    "LWV": "Chrysler",
    "LWX": "Wanxiang",
    "LW4": "Li Auto",
    "LXA": "Qipai",
    "LXD": "Dongfang Lingyun",
    "LXG": "Xuzhou Construction Machinery",
    "LXK": "Meitian",
    "LXM": "Xiashing",
    "LXN": "Link Tour",
    "LXV": "Borgward",
    "LXW": "Ford",
    "LXY": "Shineray",
    "LX6": "Huari",
    "LX8": "Xgjao",
    "LYB": "Weichai Yaxing",
    "LYD": "Kaitong",
    "LYJ": "ZhongdaYanjing",
    "LYM": "Yamaha",
    "LYS": "Vmoto",
    "LYU": "BAIC",
    "LYV": "Volvo",
    "LY4": "Yingang",
    "LZE": "Isuzu",
    "LZF": "Iveco",
    "LZG": "Shaanxi",
    "LZK": "Sinotruk",
    "LZL": "Zengcheng Haili",
    "LZM": "MAN",
    "LZP": "Zhongshan Guochi",
    "LZS": "Zongshen",
    "LZU": "Isuzu",
    "LZW": "SAIC",
    "LZY": "Yutong",
    "LZZ": "Sinotruk",
    "LZ0": "Wuzheng",
    "LZ4": "Linzhi Shangyang",
    "LZ9/LZX": "Raysince",
    "L1K": "Hengtong",
    "L1N": "XPeng",
    "L10": "Geely",
    "L2B": "Baodiao",
    "L2C": "Land Rover",
    "L3H": "Shanxi Victory",
    "L37": "Daixi Zhenhua",
    "L4B": "Xingyue",
    "L4F": "Eagle Electric",
    "L4H": "Longjia",
    "L4S": "Xingyue",
    "L4Y": "Qingqi",
    "L5C": "Kangdi",
    "L5E": "Zoomlion",
    "L5K": "Yongkang Easy",
    "L5N": "Taotao",
    "L5Y": "Zhongneng",
    "L6F": "Liangzi",
    "L6J": "Kayo",
    "L6K": "Howhit",
    "L6T": "Lynk & Co",
    "L66": "Granton",
    "L82": "Baotian",
    "L85": "Yongkang Huabao",
    "L8A": "Jinhua Youngman",
    "L8X": "Summit Huawin",
    "L8Y": "Jonway",
    "L9G": "Guangtong",
    "L9N": "Taotao",
    "MAA": "Kawasaki",
    "MAB": "Mahindra",
    "MAC": "Mahindra",
    "MAH": "Fiat",
    "MAJ": "Ford",
    "MAK": "Honda",
    "MAL": "Hyundai",
    "MAN": "Eicher Polaris Multix",
    "MAT": "Tata",
    "MA1": "Mahindra",
    "MA3": "Suzuki",
    "MA6": "GM",
    "MA7": "Mitsubishi",
    "MA8": "Daewoo",
    "MBF": "Royal Enfield",
    "MBH": "Nissan",
    "MBJ": "Toyota",
    "MBK": "MAN",
    "MBL": "Hero",
    "MBR": "Mercedes-Benz",
    "MBU": "Swaraj",
    "MBV": "Premier",
    "MBX": "Piaggio",
    "MBY": "Asia Motor Works",
    "MB1": "Ashok Leyland",
    "MB2": "Hyundai",
    "MB7": "Mahindra",
    "MB8": "Suzuki",
    "MCA": "Fiat",
    "MCB": "GM",
    "MCD": "Mahindra",
    "MCG": "Atul Auto",
    "MCL": "International Cars And",
    "MC1": "Force",
    "MC2": "Volvo",
    "MC4": "Dilip Chhabria Design",
    "MC9/RE1": "Reva Electric",
    "MDE": "Kinetic Engineering",
    "MDH": "Nissan",
    "MDT": "Kerala",
    "MD2": "Husqvarna",
    "MD6": "TVS",
    "MD7": "LML",
    "MD9": "Shuttle",
    "MEC": "Daimler",
    "MEE": "Renault",
    "MEG": "Harley-Davidson",
    "MER": "Benelli",
    "MES": "Mahindra",
    "MET": "Piaggio",
    "MEX": "Volkswagen",
    "ME1": "Yamaha",
    "ME3": "Royal Enfield",
    "ME4": "Honda",
    "MYH": "Ather",
    "MZB": "Kia",
    "MZD": "Classic Legends – Jawa",
    "MZZ": "Citroen",
    "MZ7": "MG",
    "M3G": "Isuzu",
    "M6F": "UM Lohia Two Wheelers",
    "MF3": "Hyundai",
    "MHD": "Suzuki",
    "MHF": "Toyota",
    "MHK": "Daihatsu",
    "MHL": "Mercedes-Benz",
    "MHR": "Honda",
    "MHY": "Suzuki",
    "MH1": "Honda",
    "MH3": "Yamaha",
    "MH4": "Kawasaki",
    "MH8": "Suzuki",
    "MJB": "GM",
    "MKF": "Sokonindo",
    "MK2": "Mitsubishi",
    "MK3": "SGMW",
    "MLB": "Yamaha",
    "MLC": "Suzuki",
    "MLE": "Yamaha",
    "MLH": "Honda",
    "MLW": "Sco",
    "MLY": "Harley-Davidson",
    "ML0": "Ducati",
    "ML3": "Mitsubishi",
    "ML5": "Kawasaki",
    "MMA": "Mitsubishi",
    "MMB": "Mitsubishi",
    "MMC": "Mitsubishi",
    "MMD": "Mitsubishi",
    "MME": "Mitsubishi",
    "MMF": "BMW",
    "MML": "MG",
    "MMM": "Chevrolet",
    "MMR": "Subaru",
    "MMS": "Suzuki",
    "MMT": "Mitsubishi",
    "MMU": "Holden",
    "MM0": "Mazda",
    "MM6": "Mazda",
    "MM7": "Mazda",
    "MM8": "Mazda",
    "MNA": "Ford",
    "MNB": "Ford",
    "MNC": "Ford",
    "MNK": "Hino",
    "MNT": "Nissan",
    "MNU": "Great Wall Motor",
    "MN3": "Mitsubishi",
    "MPA": "Holden",
    "MPB": "Ford",
    "MP1": "Isuzu",
    "MP2": "Mazda",
    "MP3": "Mitsubishi",
    "MP5": "Foton",
    "MRH": "Honda",
    "MRT": "Neta",
    "MR0": "Toyota",
    "MR1": "Toyota",
    "MR2": "Toyota",
    "MR3": "Toyota",
    "MS0": "Super Seven Stars",
    "MS1": "Super Seven Stars Automotive",
    "MS3": "Suzuki",
    "MXB": "Saryarka AvtoProm",
    "MXL": "Yutong",
    "MXV": "Ural",
    "MX3": "Hyundai",
    "NAA": "Iran Khodro",
    "NAC": "Mammut",
    "NAD": "Škoda",
    "NAL": "Maral Sanat Jarvid",
    "NAP": "Pars Khodro",
    "NAS": "SAIPA",
    "NC0": "Oghab Afshan",
    "NC9/": "VIRA",
    "ND9/345": "Oghab Afshan",
    "NFB": "Honda",
    "NG3": "Lucky",
    "NLA": "Honda",
    "NLC": "Askam Kamyon",
    "NLE": "Mercedes-Benz",
    "NLF": "Koluman",
    "NLH": "Hyundai",
    "NLJ": "Hyundai",
    "NLN": "Karsan",
    "NLR": "Otokar",
    "NLT": "Temsa",
    "NLZ": "Tezeller",
    "NL1": "TOGG",
    "NL2": "HABAS",
    "NMA": "MAN",
    "NMB": "Mercedes-Benz",
    "NMC": "BMC",
    "NMH": "Honda",
    "NMS": "Otoyol San.",
    "NMT": "Toyota",
    "NM0": "Ford",
    "NM1": "Renault",
    "NM4": "Tofaş",
    "NNA": "Isuzu",
    "NNN": "Gépébus Oréos",
    "NNY": "Yeksan",
    "NPM": "Seyit Usta Treyler",
    "NPR": "Oztreyler",
    "NPS": "Nursan",
    "NP8": "ÖZGÜL TREYLER",
    "NP9/002": "OKT Trailer",
    "NP9/003": "Aksoylu Trailer",
    "NP9/011": "Güleryüz",
    "NP9/021": "Dogumak",
    "NP9/022": "Alim",
    "NP9/042": "Ali Rıza Usta",
    "NP9/066": "Makinsan",
    "NP9/093": "BRF Trailer",
    "NP9/103": "Türkkar",
    "NP9/106": "Çarsan Treyler",
    "NP9/107": "Arbus Perfect",
    "NP9/108": "Guven Makina",
    "NP9/117": "Katmerciler",
    "NP9/300": "TCV",
    "NP9/258": "Ceytrayler",
    "NP9/306": "Cryocan",
    "NRE": "Bozankaya",
    "NRX": "Musoshi",
    "NRY": "Pilotcar Otomotiv",
    "NR9/028": "Micansan",
    "NR9/029": "Yilteks",
    "NR9/034": "Akia",
    "NR9/084": "Harsan",
    "NR9/257": "Vega Trailer",
    "NSA": "SamAvto",
    "NS2": "MAN",
    "NVA": "Khazar",
    "PAB": "Isuzu",
    "PAD": "Honda",
    "PE1": "Ford",
    "PE3": "Mazda",
    "PFD": "Hyundai",
    "PL1": "Proton",
    "PL8": "Hyundai",
    "PLP": "Subaru",
    "PLZ": "Isuzu",
    "PMA": "MAN",
    "PMH": "Honda",
    "PMK": "Honda",
    "PML": "Hicom",
    "PMN": "Modenas",
    "PMS": "Suzuki",
    "PMV": "Yamaha",
    "PMY": "Yamaha",
    "PM1": "MINI",
    "PM2": "Perodua",
    "PM9/": "Bufori",
    "PNA": "Peugeot",
    "PNS": "SKSBUS",
    "PNV": "Volvo",
    "PN1": "Toyota",
    "PN2": "Toyota",
    "PN8": "Nissan",
    "PPP": "Suzuki",
    "PPV": "Volkswagen",
    "PP1": "Mazda",
    "PP3": "Hyundai",
    "PRA": "Sinotruk",
    "PRH": "Chery",
    "PRX": "Kia",
    "PR8": "Ford",
    "PRN": "GAC",
    "PV3": "Ford",
    "RA1": "Steyr",
    "RA9/015": "Assri Industries",
    "LFA": "Ford",
    "LM1": "Suzuki",
    "LM4": "Suzuki",
    "LN1": "Suzuki",
    "LPR": "Yamaha",
    "RFB": "Kwang Yang",
    "RFC": "Golden Bee",
    "RFD": "Tai Ling",
    "RFG": "Sanyang",
    "RFL": "Her Chee",
    "RFT": "CPI Motor Company",
    "RFV": "Motive Power",
    "RF3": "Aeon",
    "RF5": "Yulon",
    "RF8": "EVT",
    "RGS": "Kawasaki",
    "RHA": "Ford",
    "RKJ": "Prince",
    "RKL": "Toyota",
    "RKM": "China Motor Corporation",
    "RKR": "Yamaha",
    "RKT": "Access",
    "RK3": "Honda",
    "RK7": "Kawasaki",
    "RLA": "Mitsubishi",
    "RLC": "Yamaha",
    "RLE": "Isuzu",
    "RLH": "Honda",
    "RLL": "VinFast",
    "RLM": "Mercedes-Benz",
    "RLN": "VinFast",
    "RLV": "Can-Am",
    "RL0": "Ford",
    "RL4": "Toyota",
    "RP8": "Piaggio",
    "RUN": "Auto ST6",
    "R1J": "Jiayuan",
    "R1N": "Niu Technologies",
    "R10": "ZAP",
    "R19/003": "GMI",
    "R2P": "Evoke Electric",
    "R3M": "Mangosteen",
    "R36": "HK Shansu",
    "R4N": "smart",
    "R82": "Lantu",
    "SAA": "Austin",
    "SAB": "Optare",
    "SAD": "Daimler",
    "SAF": "ERF",
    "SAH": "Honda",
    "SAJ": "Daimler",
    "SAL": "Land Rover",
    "SAM": "Morris",
    "SAR": "MG",
    "SAT": "Triumph",
    "SAX": "Rover",
    "SAY": "Norton",
    "SAZ": "Freight Rover",
    "SA3": "Ginetta",
    "SA9/": "MG",
    "SBB": "Leyland",
    "SBC": "Iveco",
    "SBF": "Nugent",
    "SBJ": "Leyland",
    "SBL": "DAF",
    "SBM": "McLaren",
    "SBS": "Scammell",
    "SBU": "United Trailers",
    "SBV": "Peterbilt",
    "SBW": "Weightlifter Bodies",
    "SB1": "Toyota",
    "SCA": "Rolls Royce",
    "SCB": "Bentley",
    "SCC": "Opel",
    "SCD": "Reliant",
    "SCE": "DeLorean",
    "SCF": "Aston Martin",
    "SCG": "Triumph",
    "SCK": "Ifor Williams Trailers",
    "SCM": "Manitowoc",
    "SCR": "London Electric Vehicle",
    "SCV": "Volvo",
    "SC5": "Wrightbus",
    "SC6": "INEOS Automotive",
    "SDB": "Talbot",
    "SDC": "SDC Trailers",
    "SDF": "Dennis",
    "SFE": "Alexander Dennis",
    "SFR": "Fruehauf",
    "SFN": "Foden",
    "SFZ": "Tesla",
    "SGA": "Avondale",
    "SGB": "Bailey",
    "SGD": "Swift",
    "SGE": "Elddis",
    "SGL": "Lunar Caravans",
    "SG4": "Coachman",
    "SHH": "Honda",
    "SHS": "Honda",
    "SH7": "INEOS Automotive",
    "SJA": "Bentley",
    "SJB": "Brian James Trailers",
    "SJK": "Infiniti",
    "SJN": "Nissan",
    "SJ1": "Ree Automotive",
    "SKA": "Opel",
    "SKB": "Berg Trailers & Trucks",
    "SKF": "Bedford",
    "SKL": "Anaig",
    "SLA": "Rolls Royce",
    "SLC": "Thwaites Dumpers",
    "SLG": "McMurtry Automotive",
    "SLN": "Niftylift",
    "SLP": "JC Bamford Excavators",
    "SLV": "Volvo",
    "SMR": "Montracon",
    "SMT": "Triumph",
    "SMW": "Cartwright",
    "SMX": "Gray",
    "SNE": "Barkas",
    "SNT": "Trabant",
    "SNZ": "MZ",
    "SPE": "ON",
    "ST3": "Calabrese",
    "SUA": "Autosan",
    "SUB": "Tramp Trail",
    "SUC": "Wiola",
    "SUD": "Wielton",
    "SUF": "Fiat",
    "SUG": "Mega Trailers",
    "SUJ": "Jelcz",
    "SUL": "FSC",
    "SUP": "Daewoo",
    "SUU": "Solaris Bus",
    "SU9/AR1": "Emtech",
    "SU9/BU1": "BODEX",
    "SU9/DE2": "Demarco",
    "SU9/EB1": "Elbo",
    "SU9/EZ1": "Enerco",
    "SU9/NC5": "Zasta",
    "SU9/NJ1": "Janmil",
    "SU9/PL1": "Plandex",
    "SU9/PN1": "Solaris Bus",
    "SU9/RE1": "Redos",
    "SU9/RE2": "Gromex",
    "SU9/TR1": "Plavec",
    "SU9/YV1": "Pilea",
    "SU9/ZC1": "Wolf",
    "SVH": "ZASŁAW",
    "SVM": "Inter",
    "SVS": "BODEX",
    "SV9/BC2": "LDS",
    "SV9/DR1": "Dromech",
    "SV9/RN1": "Rent",
    "SWH": "Temared",
    "SWR": "Weekend Trailers",
    "SWV": "NO",
    "SWZ": "Zremb",
    "SW9/BA1": "Solbus",
    "SW9/WG3": "Grew",
    "SXE": "Neptun Trailers",
    "SXM": "MELEX",
    "SXY": "Wecon",
    "SXX": "Martz",
    "SX7": "Arthur",
    "SX9/GR0": "GRAS",
    "SX9/KT1": "Kutno",
    "SX9/PN1": "Polkon",
    "SX9/SP1": "SOMMER Polska",
    "SYB": "Rydwan",
    "SYG": "Gniotpol",
    "SY1": "Neso",
    "SY9/FR1": "Feber",
    "SY9/PF1": "KEMPF",
    "SZA": "Scania",
    "SZC": "Vectrix",
    "SZL": "Boro Trailers",
    "SZN": "Przyczepy Głowacz",
    "SZR": "Niewiadów",
    "SZ9/BG1": "GALA Syriusz",
    "SZ9/PW1": "WAM",
    "SZ9/TU1": "Ovibos",
    "S19/AM0": "AMO Plant",
    "S19/EF1": "Electrify",
    "S19/MT0": "Transserviss",
    "TAW": "NAW Nutzfahrzeuggesellschaft",
    "TBS": "Boschung",
    "TCC": "Micro Compact",
    "TDM": "QUANTYA Swiss Electric Movement",
    "TEB": "Bucher Municipal",
    "TEM": "Twike",
    "TFH": "Hoch",
    "TH9/512": "Hess",
    "TJ5": "Vezeko",
    "TKP": "Panav",
    "TKX": "Agados",
    "TKY": "Metaco",
    "TK9/AH3": "Atmos Chrást",
    "TK9/AP3": "Agados",
    "TK9/HP1": "Hipocar",
    "TK9/PP7": "Paragan",
    "TK9/SL5": "SOR Libchavy",
    "TK9/SS5": "SVAN Chrudim",
    "TLJ": "Jawa Moto",
    "TMA": "Hyundai",
    "TMB": "Škoda",
    "TMC": "Hyundai",
    "TMK": "Karosa",
    "TMP": "Škoda",
    "TMT": "Tatra",
    "TM9/CA2": "Oasa",
    "TM9/SE3": "Škoda",
    "TM9/SE4": "Škoda",
    "TM9/TE6": "TEDOM",
    "TNA": "Daewoo",
    "TNE": "TAZ",
    "TNG": "LIAZ",
    "TNT": "Tatra",
    "TNU": "Tatra",
    "TN9/EE7": "Ekova",
    "TN9/VP5": "VPS",
    "TRA": "Ikarus",
    "TRC": "Csepel",
    "TRE": "Rákos",
    "TRK": "Credo bus",
    "TRR": "Rába",
    "TRU": "Audi",
    "TSB": "Ikarus",
    "TSC": "VIN Authority",
    "TSE": "Ikarus Egyedi Autobuszgyar",
    "TSF": "Alfabusz",
    "TSM": "Suzuki",
    "TSY": "Keeway",
    "TS9/111": "NABI Autóbuszipari",
    "TS9/130": "Enterprise",
    "TS9/131": "MJT",
    "TS9/156": "Ikarus",
    "TS9/167": "Hungarian",
    "TS9/170": "Csaba Metál",
    "TT9/117": "Ikarus Egyedi",
    "TT9/123": "Ikarus Global",
    "TWG": "CaetanoBus",
    "TW0": "CaetanoBus",
    "TW1": "Toyota",
    "TW2": "Ford",
    "TW4": "UMM",
    "TW6": "Citroën",
    "TW7": "MINI",
    "TX5": "MINI",
    "TX9/046": "Riotrailer",
    "TYA": "Mitsubishi",
    "TYB": "Mitsubishi",
    "T3C": "Lohr Backa Topola",
    "T49/BG7": "FAP",
    "T49/BH8": "Megabus",
    "T49/BM2": "Feniksbus",
    "T49/V16": "MAZ",
    "T7A": "Ebusco",
    "UA1": "AUSA Center",
    "UA4": "mobility",
    "UCY": "Silence Urban Ecomobility",
    "UD3": "Granalu truck trailers",
    "UHE": "Scanvogn",
    "UHL": "let",
    "UH2": "Brenderup",
    "UH9/DA3": "DAB",
    "UH9/FK1": "Dapa Trailer",
    "UH9/HF1": "HFR Trailer",
    "UH9/HM1": "HMK Bilcon",
    "UH9/NS1": "Nopa",
    "UH9/NT1": "Nordic Trailer",
    "UH9/VM2": "VM Tarm",
    "UJG": "Garia",
    "UKR": "Hero",
    "UMT": "MTDK",
    "UN1": "Ford",
    "UN9/089": "Brian Noone Ltd.",
    "UU1": "Dacia",
    "UU2": "Oltcit",
    "UU3": "ARO",
    "UU4": "Roman",
    "UU5": "Rocar",
    "UU6": "Daewoo",
    "UU7": "Euro Bus Diamond",
    "UU9": "Astra",
    "UVW": "UMM",
    "UV9/AT1": "ATP Trucks",
    "UWR": "Robus Reșița",
    "UZT": "UTB",
    "U1A": "Sanos",
    "U1V": "VDL Van Hool",
    "U5Y": "Kia",
    "U59/AS0": "ASKO",
    "U6A": "Granus",
    "U6Y": "Kia",
    "U69/NL1": "Novoplan",
    "U69/SB1": "SlovBus",
    "U69/TR8": "Troliga",
    "VAG": "Daimler",
    "VAH": "Hangler",
    "VAK": "Kässbohrer Transport Technik",
    "VAN": "Daimler",
    "VAV": "Schwarzmüller",
    "VAX": "Schwingenschlogel",
    "VA0": "ÖAF",
    "VA4": "KSR",
    "VA9/GS0": "Gsodam Fahrzeugbau",
    "VA9/ZT0": "Berger Fahrzeugtechnik",
    "VBF": "Zel",
    "VBK": "Husqvarna",
    "VCF": "Fisker",
    "VFA": "Renault",
    "VFG": "Caravelair",
    "VFK": "Fruehauf",
    "VFN": "Trailor",
    "VF1": "Renault",
    "VF2": "Renault",
    "VF3": "Peugeot",
    "VF4": "Talbot",
    "VF5": "Iveco",
    "VF6": "Renault",
    "VF7": "Citroën",
    "VF8": "Matra",
    "VF9/024": "Legras",
    "VF9/049": "G. Magyar",
    "VF9/063": "Maisonneuve",
    "VF9/132": "Jean CHEREAU S.A.S.",
    "VF9/300": "EvoBus",
    "VF9/435": "Merceron",
    "VF9/519": "Hommell",
    "VF9/607": "Mathieu",
    "VF9/673": "Venturi",
    "VF9/795": "Bugatti",
    "VF9/848": "G. Magyar",
    "VF9/880": "Bolloré Bluebus",
    "VF9/938": "SAFRA",
    "VGA": "Peugeot",
    "VGT": "ASCA",
    "VGU": "Trouillet",
    "VGW": "BSLT",
    "VGY": "Lohr",
    "VG5": "MBK",
    "VG6": "Renault",
    "VG7": "Renault",
    "VG8": "Renault",
    "VG9/019": "Naya",
    "VG9/061": "NTL Aptis",
    "VHR": "Robuste",
    "VHX": "Potain",
    "VH1": "Benalu SAS",
    "VH8": "Microcar",
    "VJR": "Ligier",
    "VJY": "Gruau",
    "VJ1": "Heuliez",
    "VJ2": "Mia Electric",
    "VJ4": "Gruau",
    "VKD": "Cheval Liberté",
    "VK1": "SEG",
    "VK2": "Grandin",
    "VK8": "Venturi",
    "VLG": "Mega",
    "VLU": "Scania",
    "VL4": "Citroen",
    "VMK": "Renault",
    "VMS": "Automobiles Chatenet",
    "VMT": "SECMA",
    "VMW": "Gépébus Oréos 55",
    "VM3": "Lamberet",
    "VN1": "Opel",
    "VN4": "Voxan",
    "VNE": "Iveco",
    "VNK": "Daihatsu",
    "VNV": "Renault",
    "VRW": "Goupil",
    "VR1": "DS Automobiles",
    "VR3": "Peugeot",
    "VR7": "Citroën",
    "VPL": "Nosmoke S.A.S",
    "VP3": "G. Magyar",
    "VXE": "Opel",
    "VXF": "Fiat",
    "VXK": "Opel",
    "VYC": "Lancia",
    "VYF": "Fiat",
    "VYJ": "Ram",
    "VYS": "Renault",
    "VZ2": "Avtomontaža",
    "UA2": "Iveco",
    "VSA": "Mercedes-Benz",
    "VSC": "Talbot",
    "VSE": "Suzuki",
    "VSF": "Santana",
    "VSK": "Nissan",
    "VSR": "Leciñena",
    "VSS": "Cupra",
    "VSX": "Opel",
    "VSY": "Renault",
    "VS1": "Pegaso",
    "VS5": "Renault",
    "VS6": "Ford",
    "VS7": "Citroën",
    "VS8": "Peugeot",
    "VS9/001": "Setra Seida",
    "VS9/011": "Advanced Design Tramontana",
    "VS9/016": "Irizar",
    "VS9/019": "Cobos Hermanos",
    "VS9/031": "Carrocerias Ayats",
    "VS9/032": "Parcisa",
    "VS9/044": "Beulas",
    "VS9/047": "Indox",
    "VS9/052": "Montull",
    "VS9/057": "SOR Ibérica",
    "VS9/072": "Mecanicas Silva",
    "VS9/098": "Sunsundegui",
    "VS9/172": "EvoBus Iberica",
    "VS9/917": "Nogebus",
    "VTD": "Honda",
    "VTH": "Derbi",
    "VTL": "Yamaha",
    "VTM": "Honda",
    "VTP": "Rieju S.A.",
    "VTR": "Gas Gas",
    "VTT": "Suzuki",
    "VVC": "SOR Ibérica",
    "VVG": "Tisvol",
    "VV1": "Lecitrailer",
    "VV5": "Ball",
    "VV9/": "TAURO Sport Auto",
    "VV9/010": "Castrosúa",
    "VV9/125": "Indetruck",
    "VV9/130": "Vectia Mobility bus",
    "VV9/359": "Suiza",
    "VWA": "Nissan",
    "VWF": "Guillén",
    "VWL": "Indox",
    "VWV": "Volkswagen",
    "VXY": "Neobus",
    "VX1": "Zastava",
    "V1Y": "FAS Sanos",
    "V2X": "Ikarbus",
    "V31": "Tvornica Autobusa Zagreb",
    "V34": "Crobus",
    "V39/AB8": "Rimac Automobili",
    "V39/CB3": "Eurobus",
    "V39/WB4": "Rasco",
    "V6A": "Bestnet AS",
    "V6B": "Trailer",
    "V6T": "Verge",
    "V61": "Respo Trailers",
    "WAC": "Audi",
    "WAF": "Ackermann",
    "WAG": "Neoplan",
    "WAP": "Alpina",
    "WAU": "Audi",
    "WA1": "Audi",
    "WBA": "BMW",
    "WBC": "Boom Trikes",
    "WBJ": "Bitter",
    "WBK": "Böcker Maschinenwerke GmbH",
    "WBL": "Blumhardt",
    "WBS": "BMW",
    "WBU": "Bürstner",
    "WBX": "BMW",
    "WBY": "BMW",
    "WB0": "Böckmann Fahrzeugwerke GmbH",
    "WB1": "BMW",
    "WB2": "Blyss",
    "WB3": "BMW",
    "WB4": "BMW",
    "WB5": "BMW",
    "WCD": "Freightliner",
    "WCM": "Wilcox",
    "WDA": "Mercedes-Benz",
    "WDB": "Mercedes-Benz",
    "WDC": "Mercedes-Benz",
    "WDD": "Mercedes-Benz",
    "WDF": "Mercedes-Benz",
    "WDP": "Freightliner",
    "WDR": "Freightliner",
    "WDT": "Dethleffs",
    "WDW": "Dodge",
    "WDX": "Dodge",
    "WDY": "Freightliner",
    "WDZ": "Mercedes-Benz",
    "WD0": "Dodge",
    "WD1": "Freightliner",
    "WD2": "Freightliner",
    "WD3": "Mercedes-Benz",
    "WD4": "Mercedes-Benz",
    "WD5": "Freightliner",
    "WD6": "Freightliner",
    "WD7": "Freightliner",
    "WD8": "Dodge",
    "WEB": "Evobus GmbH",
    "WEG": "Ablinger",
    "WEL": "e.GO Mobile AG",
    "WFB": "Feldbinder Spezialfahrzeugwerke GmbH",
    "WFC": "Fendt",
    "WFD": "Fliegl Trailer",
    "WFN": "Tadano Faun GmbH",
    "WF0": "Ford",
    "WF1": "Merkur",
    "WGB": "Göppel Bus GmbH",
    "WG0": "Goldhofer AG",
    "WHB": "Hobby",
    "WHD": "Humbaur GmbH",
    "WHW": "Hako GmbH",
    "WHY": "Hymer",
    "WH7": "Hüfferman",
    "WJM": "Iveco",
    "WJR": "Irmscher",
    "WKE": "Krone",
    "WKK": "Setra",
    "WKN": "Knaus",
    "WKV": "Kässbohrer",
    "WK0": "Kögel",
    "WLA": "Langendorf",
    "WLF": "Liebherr",
    "WMA": "MAN",
    "WME": "smart",
    "WMG": "Demag Cranes",
    "WMM": "Karl Müller GmbH",
    "WMU": "Hako",
    "WMW": "MINI",
    "WMX": "Mercedes-AMG",
    "WMZ": "MINI",
    "WNA": "Next.e.GO Mobile SE",
    "WP0": "Porsche",
    "WP1": "Porsche",
    "WRA": "Renders",
    "WSE": "STEMA Metalleichtbau GmbH",
    "WSJ": "System Trailers",
    "WSK": "Cargobull Gotha",
    "WSM": "Cargobull",
    "WSV": "Aebi Schmidt",
    "WS5": "StreetScooter",
    "WS7": "Sono",
    "WTA": "Tabbert",
    "WUA": "Audi Sport GmbH",
    "WU1": "Audi Sport GmbH",
    "WVG": "Volkswagen",
    "WVM": "MAN",
    "WVP": "Viseon",
    "WVW": "Volkswagen",
    "WV1": "Volkswagen",
    "WV2": "Volkswagen",
    "WV3": "Volkswagen",
    "WV4": "Volkswagen",
    "WV5": "Volkswagen",
    "WWA": "Wachenhut",
    "WWC": "WM Meyer",
    "WZ1": "Toyota",
    "W0D": "Obermaier",
    "W0L": "Opel",
    "W0V": "Opel",
    "W04": "Buick",
    "W06": "Cadillac",
    "W08": "Saturn",
    "W09/A55": "Artega",
    "W09/A71": "Apollo",
    "W09/B09": "Bitter",
    "W09/B16": "Brabus",
    "W09/B48": "Bultmann",
    "W09/B91": "Boerner",
    "W09/C09": "Carnehl Fahrzeugbau",
    "W09/D04": "DOLL",
    "W09/D05": "Drögmöller",
    "W09/D17": "Dinkel",
    "W09/E04": "Eder",
    "W09/E27": "Esterer",
    "W09/E32": "GE",
    "W09/E45": "Eurotank",
    "W09/F46": "FSN Fahrzeugbau",
    "W09/F57": "Twike",
    "W09/G10": "GOFA",
    "W09/G64": "Gumpert",
    "W09/H10": "Heitling Fahrzeugbau",
    "W09/H21": "Dietrich Hisle GmbH",
    "W09/H46": "Hendricks",
    "W09/H49": "H",
    "W09/J02": "Isdera",
    "W09/K27": "Krupp",
    "W09/L05": "Liebherr",
    "W09/L06": "LMC Caravan",
    "W09/M09": "Meierling",
    "W09/M29": "MAFA",
    "W09/M79": "MKF Matallbau",
    "W09/N22": "Eurotrailer",
    "W09/P13": "Pagenkopf",
    "W09/P72": "De Tomaso Automobili",
    "W09/R06": "RUF",
    "W09/R14": "Rancke",
    "W09/R27": "Gebr. Recker Fahrzeugbau",
    "W09/R30": "Reisch",
    "W09/R38": "Rewaco",
    "W09/SG0": "Sileo",
    "W09/SG1": "SEKA",
    "W09/S24": "Sommer",
    "W09/S25": "Spermann",
    "W09/S27": "Schröder",
    "W09/W11": "Wilken",
    "W09/W14": "Weka",
    "W09/W16": "Wellmeyer",
    "W09/W20": "Kurt Willig GmbH",
    "W09/W29": "Wiese",
    "W09/W35": "Wecon GmbH",
    "W09/W46": "Metall",
    "W09/W59": "Wiesmann",
    "W09/W70": "Wüllhorst",
    "W09/W86": "Web Trailer GmbH",
    "W09/004": "ORTEN Fahrzeugbau",
    "W1A": "smart",
    "W1H": "Freightliner",
    "W1K": "Mercedes-Benz",
    "W1N": "Mercedes-Benz",
    "W1T": "Mercedes-Benz",
    "W1V": "Mercedes-Benz",
    "W1W": "Mercedes-Benz",
    "W1X": "Mercedes-Benz",
    "W1Y": "Mercedes-Benz",
    "W1Z": "Mercedes-Benz",
    "W2W": "Freightliner",
    "W2X": "Freightliner",
    "W2Y": "Freightliner",
    "W2Z": "Freightliner",
    "XDN": "Mercedes Sprinter Classic",
    "XD2": "CTTM Cargoline",
    "XEA": "AmberAvto",
    "XE2": "AMKAR Automaster",
    "XF9/B24": "NK Trailers",
    "XF9/D44": "Militsis",
    "XF9/J03": "Christos Nezis",
    "XF9/J63": "Kaoussis",
    "XG3": "Petros Petropoulos",
    "XG4": "Mpitis",
    "XG5": "Stavropoulos trailers",
    "XG6": "MGK Hellenic Motor",
    "XG8": "Gorgolis SA",
    "XG9/B01": "Sfakianakis",
    "XG9/H33": "Rappas Trailer",
    "XG9/H51": "Eurotrailer Tourlakopoulos",
    "XG9/H92": "Diamantis N.",
    "XΗ9/B21": "ELVO bus",
    "XH9/H08": "Poseidonas Litsakis",
    "XH9/H34": "Wheels",
    "XJY": "Bonum",
    "XJ4": "PKTS",
    "XKM": "Volgabus",
    "XLA": "DAF",
    "XLB": "Volvo",
    "XLC": "Ford",
    "XLD": "Pacton Trailers",
    "XLE": "Scania",
    "XLJ": "Anssems",
    "XLK": "Burg Trailer Service BV",
    "XLR": "DAF",
    "XLV": "DAF",
    "XLW": "Terberg Benschop BV",
    "XL3": "Ebusco",
    "XL4": "Lightyear",
    "XL9/002": "Jumbo Groenewegen",
    "XL9/003": "Autobusfabriek Bova BV",
    "XL9/004": "G.S. Meppel",
    "XL9/007": "Broshuis BV",
    "XL9/010": "Ginaf",
    "XL9/017": "Van Eck",
    "XL9/021": "Donkervoort",
    "XL9/033": "Wijer",
    "XL9/039": "Talson",
    "XL9/042": "Den Oudsten Bussen",
    "XL9/052": "Witteveen",
    "XL9/055": "Fripaan",
    "XL9/068": "Vogelzang",
    "XL9/069": "Kraker",
    "XL9/073": "Zwalve",
    "XL9/084": "Vocol",
    "XL9/092": "Bulthuis",
    "XL9/103": "TEC",
    "XL9/109": "Groenewold Carrosseriefabriek B.V.",
    "XL9/150": "Univan",
    "XL9/251": "Spierings Mobile Cranes",
    "XL9/320": "VDL Bova",
    "XL9/355": "Berdex",
    "XL9/363": "Spyker",
    "XL9/495": "Combi",
    "XL9/508": "Talson",
    "XL9/530": "Ebusco",
    "XMC": "Mitsubishi",
    "XMD": "Mitsubishi",
    "XMG": "VDL Bus International",
    "XMR": "Nooteboom Trailers",
    "XM4": "RAVO Holding B.V.",
    "XNB": "Mitsubishi",
    "XNC": "Mitsubishi",
    "XNJ": "Broshuis",
    "XNL": "VDL Bus",
    "XNT": "Pacton Trailers",
    "XN1": "Kraker Trailers Axel B.V.",
    "XPN": "Knapen Trailers",
    "XP7": "Tesla",
    "XRY": "TEC",
    "XTA": "Lada",
    "XTB": "Moskvitch",
    "XTC": "KAMAZ",
    "XTD": "LuAZ",
    "XTE": "ZAZ",
    "XTF": "GolAZ",
    "XTH": "GAZ",
    "XTJ": "Lada",
    "XTK": "IzhAvto",
    "XTM": "MAZ",
    "XTP": "Ural",
    "XTS": "ChMZAP",
    "XTT": "UAZ",
    "XTU": "Trolza",
    "XTW": "LAZ",
    "XTY": "LiAZ",
    "XTZ": "ZiL",
    "XUF": "General Motors",
    "XUS": "Nizhegorodets",
    "XUU": "Chevrolet",
    "XUV": "Avtotor (DFSK",
    "XUZ": "InterPipeVAN",
    "XU6": "Avtodom",
    "XVG": "MARZ",
    "XVU": "Start",
    "XW7": "Toyota",
    "XW8": "Volkswagen",
    "XWB": "BAIC",
    "XWE": "Kia",
    "XWF": "Chevrolet",
    "XX3": "Ujet",
    "XZB": "SIMAZ",
    "XZE": "Specpricep",
    "XZG": "Great Wall Motor",
    "XZP": "Gut Trailer",
    "XZT": "FoxBus minibus",
    "X1D": "RAF",
    "X1E": "KAvZ",
    "X1F": "NefAZ",
    "X1M": "PAZ",
    "X1P": "Ural",
    "X2L": "Fox Trailer",
    "X21": "S",
    "X4K": "Volgabus",
    "X4T": "Sommer",
    "X4X": "Avtotor",
    "X5A": "UralSpetzTrans",
    "X6D": "AVTO",
    "X6S": "TZA",
    "X7L": "Renault",
    "X7M": "Hyundai",
    "X89/AD4": "VMZ",
    "X89/BF8": "Rosvan",
    "X89/CU2": "EvoBus Russland",
    "X89/DJ2": "VMK",
    "X89/EY4": "Brabill minibus",
    "X89/FF6": "Lotos",
    "X89/FY1": "Sherp",
    "X8J": "Ural Motorcycles",
    "X8U": "Scania",
    "X9F": "Ford",
    "X9L": "GM",
    "X9N": "Samoltor minibus",
    "X9P": "Volvo",
    "X9W": "Brilliance",
    "X9X": "Great Wall Motors",
    "X96": "GAZ",
    "X99/000": "Marussia",
    "X90": "GRAZ trailers",
    "X0T": "Tonar trailers",
    "YAF": "Faymonville special transport",
    "YAM": "Faymonville",
    "YAR": "Toyota",
    "YA2": "Atlas Copco",
    "YA5": "Renders",
    "YA9/": "Lambrecht Constructie NV",
    "YA9/111": "OVA",
    "YA9/121": "Atcomex",
    "YA9/128": "EOS",
    "YA9/139": "ATM Maaseik",
    "YA9/168": "Forthomme s.a.",
    "YA9/169": "Automobiles Gillet",
    "YA9/180": "EOS",
    "YA9/191": "Stokota",
    "YA9/195": "Denolf",
    "YBC": "Toyota",
    "YBD": "Addax",
    "YBW": "Volkswagen",
    "YB1": "Volvo",
    "YB2": "Volvo",
    "YB3": "Volvo",
    "YB4": "LAG Trailers N.V.",
    "YB6": "Jonckheere",
    "YCM": "Mazda",
    "YC1": "Honda",
    "YC3": "Eduard Trailers",
    "YD3": "Chateau Caravans",
    "YE1": "Van Hool trailers",
    "YE2": "Van Hool",
    "YE6": "STAS trailers",
    "YE7": "Turbo's Hoet trailers",
    "YF1": "Närko trailers",
    "YF3": "NTM trailers",
    "YF9/050": "JYKI trailers",
    "YGU": "Trailer",
    "YH1": "Solifer caravans",
    "YH2": "BRP Finland",
    "YH4": "Fisker Automotive",
    "YK1": "Valmet Finland",
    "YK2": "Sisu Auto",
    "YK7": "Sisu Auto",
    "YK9/003": "Kabus",
    "YK9/008": "Lahden Autokori",
    "YK9/016": "Linkker",
    "YSC": "Cadillac",
    "YSM": "Polestar",
    "YSP": "Volta Trucks AB",
    "YSR": "Polestar",
    "YS2": "Scania",
    "YS3": "Saab",
    "YS4": "Scania",
    "YS5": "OmniNova minibus",
    "YS7": "Solifer recreational",
    "YS9/KV1": "Backaryd minibus",
    "YTN": "Saab made by NEVS",
    "YT7": "Kabe caravans",
    "YT9/007": "Koenigsegg",
    "YT9/034": "Carvia",
    "YU1": "Fogelsta",
    "YU7": "Husaberg",
    "YVV": "WiMa 442 EV",
    "YV1": "Volvo",
    "YV2": "Volvo",
    "YV3": "Volvo",
    "YV4": "Volvo",
    "YV5": "Volvo",
    "YYB": "Tysse trailers",
    "YYC": "Think Nordic",
    "YY9/017": "Skala Fabrikk trailers",
    "Y29/005": "Buddy Electric",
    "Y3D": "MTM trailers",
    "Y3F": "Lida Buses Neman",
    "Y3J": "Belkommunmash",
    "Y3K": "Neman",
    "Y3M": "MAZ",
    "Y3W": "VFV by Unison",
    "Y39/047": "M minibus",
    "Y39/051": "Master minibus",
    "Y39/052": "Aktriya minibus",
    "Y39/072": "Klassikbus minibus",
    "Y39/074": "Alterra minibus",
    "Y39/135": "EuroDjet minibus",
    "Y39/240": "Alizana minibus",
    "Y39/241": "RSBUS minibus",
    "Y39/323": "AVTO minibus",
    "Y4F": "Ford",
    "Y4K": "Geely",
    "Y6B": "Iveco",
    "Y6D": "ZAZ",
    "Y6E": "LAZ Ukraine",
    "Y6J": "Bogdan",
    "Y6L": "Hyundai",
    "Y6U": "Škoda",
    "Y6W": "PGFM trailers",
    "Y6Y": "LEV trailers",
    "Y69/B19": "Stryi Avto",
    "Y69/B98": "VESTT trailers",
    "Y69/C49": "TAD trailers",
    "Y69/D75": "Barrel Dash trailers",
    "Y7A": "KrAZ",
    "Y7B": "Bogdan",
    "Y7C": "Great Wall",
    "Y7D": "GAZ",
    "Y7F": "Boryspil Bus Factory",
    "Y7S": "Tech trailers",
    "Y7W": "Geely",
    "Y7X": "Ruta minibus",
    "Y79/A23": "OdAZ trailers",
    "Y79/B21": "Everlast trailers",
    "Y79/B65": "Avtoban trailers",
    "Y8A": "LAZ",
    "Y8H": "UNV Leader trailers",
    "Y8S": "Alekseevka Ximmash trailers",
    "Y8X": "GAZ",
    "Y89/A98": "VARZ trailers",
    "Y89/B75": "Knott trailers",
    "Y89/C65": "Electron Ukraine",
    "Y9A": "PAVAM trailers",
    "Y9H": "LAZ",
    "Y9M": "AMS trailers",
    "Y9T": "Dnipro trailers",
    "Y9W": "Pragmatec trailers",
    "Y9Z": "Renault",
    "Y99/B32": "Santey trailers",
    "Y99/E21": "Trans trailers",
    "Y99/C79": "Electron",
    "ZAA": "Autobianchi",
    "ZAC": "Dodge",
    "ZAH": "Rolfo SpA",
    "ZAJ": "Trigano",
    "ZAM": "Maserati",
    "ZAP": "Piaggio",
    "ZAR": "Alfa Romeo",
    "ZAS": "Alfa Romeo Alfasud",
    "ZAX": "Zorzi trailers",
    "ZA4": "Omar trailers",
    "ZA9/A12": "2003)",
    "ZA9/A17": "Carrozzeria Luigi Dalla Via",
    "ZA9/A18": "De Simon",
    "ZA9/A33": "Bucher Schörling sweeper",
    "ZA9/B09": "Mauri Bus System",
    "ZA9/B34": "Mistrall Siloveicoli trailers",
    "ZA9/B45": "Bolgan trailers",
    "ZA9/B49": "OMSP Macola trailers",
    "ZA9/B95": "Carrozzeria Autodromo Modena",
    "ZA9/C38": "Dulevo sweeper",
    "ZA9/D38": "Cizeta Automobili",
    "ZA9/D39": "Bugatti Automobili",
    "ZA9/D50": "Italdesign Giugiaro",
    "ZA9/E15": "Tecnobus",
    "ZA9/E73": "Sitcar",
    "ZA9/E88": "Cacciamali",
    "ZA9/F16": "OMT trailers",
    "ZA9/F21": "FGM trailers",
    "ZA9/F48": "Rampini Carlo S.p.A.",
    "ZA9/F76": "Pagani Automobili",
    "ZA9/G97": "EPT Horus",
    "ZA9/H02": "O.ME.P.S. trailers",
    "ZA9/H44": "technik machine trailers",
    "ZA9/J21": "VRV trailers",
    "ZA9/J93": "Barbi",
    "ZA9/K98": "Esagono Energia",
    "ZA9/M09": "Italdesign Automobili Speciali",
    "ZA9/M27": "Dallara Stradale",
    "ZA9/M91": "Automobili Pininfarina",
    "ZA9/180": "De Simon",
    "ZA0": "Acerbi trailers",
    "ZBA": "Piacenza trailers",
    "ZBB": "Bertone",
    "ZBD": "InBus",
    "ZBN": "Benelli",
    "ZBW": "Fissore Magnum",
    "ZB3": "Cardi trailers",
    "ZCB": "E. Bartoletti trailers",
    "ZCF": "Iveco",
    "ZCG": "Cagiva",
    "ZCM": "BredaMenarinibus",
    "ZCN": "Astra Veicoli Industriali",
    "ZCV": "Vibreti trailers",
    "ZCZ": "BredaBus",
    "ZC1": "AnsaldoBreda",
    "ZC2": "Chrysler",
    "ZDC": "Honda",
    "ZDF": "Ferrari Dino",
    "ZDJ": "ACM Biagini",
    "ZDM": "Ducati",
    "ZDT": "De Tomaso Modena",
    "ZDY": "Cacciamali",
    "ZD0": "Yamaha",
    "ZD3": "Beta",
    "ZD4": "Aprilia",
    "ZD5": "Casalini",
    "ZEB": "Ellebi trailers",
    "ZEH": "Trigano",
    "ZES": "Bimota",
    "ZEX": "TM Racing",
    "ZE5": "Carmosino trailers",
    "ZFA": "Fiat",
    "ZFB": "Fiat",
    "ZFC": "Fiat",
    "ZFE": "KL",
    "ZFF": "Ferrari",
    "ZFJ": "Carrozzeria Pezzaioli trailers",
    "ZFM": "Fantic",
    "ZFR": "Pininfarina",
    "ZF4": "Qvale",
    "ZGA": "Iveco",
    "ZGP": "Merker trailers",
    "ZGU": "Moto Guzzi",
    "ZG2": "FAAM",
    "ZHU": "Husqvarna",
    "ZHW": "2003– )",
    "ZHZ": "Menci trailers",
    "ZH5": "FB Mondial",
    "ZJM": "Malaguti",
    "ZJN": "Innocenti",
    "ZJT": "Italjet",
    "ZKC": "Ducati",
    "ZKH": "Husqvarna",
    "ZLA": "Lancia",
    "ZLF": "Tazzari GL SpA",
    "ZLM": "Moto Morini",
    "ZLV": "Laverda",
    "ZNN": "Energica",
    "ZN0": "Motorcycles",
    "ZN3": "Iveco",
    "ZN6": "Maserati",
    "ZPB": "Lamborghini",
    "ZPY": "DR",
    "ZP6": "XEV",
    "ZP8": "Regis",
    "ZRG": "Tazzari GL Imola SpA",
    "ZR1": "Microlino",
    "ZSG": "Ferrari",
    "ZX1": "TAM bus Slovenia",
    "ZX9/KU0": "K-Bus",
    "ZX9/DUR": "TAM",
    "ZX9/TV0": "TAM",
    "ZY1": "Adria RV",
    "ZY9/002": "Gorica trailers",
    "ZZ1": "Tomos",
    "Z29/555": "Vozila FLuid trailers",
    "Z39/008": "Autogalantas trailers",
    "Z39/009": "Patikima Linija",
    "Z6F": "Ford",
    "Z7C": "Luidor",
    "Z7N": "KAvZ",
    "Z7T": "RoAZ",
    "Z7X": "Isuzu",
    "Z76": "SEMAZ",
    "Z8M": "Marussia",
    "Z8N": "Nissan",
    "Z8T": "PCMA Rus",
    "Z8Y": "Nasteviya",
    "Z9B": "Hyundai",
    "Z9M": "Mercedes-Benz",
    "Z9N": "NN (Iveco) (Russia)",
    "Z94": "Hyundai",
    "Z07": "Volgabus",
    "1A4": "Chrysler",
    "1A8": "Chrysler",
    "1A9/007": "Advance Mixer Inc.",
    "1A9/111": "Amerisport Inc.",
    "1A9/398": "Ameritech (McLaren F1",
    "1A9/569": "American Custom Golf Cars Inc.",
    "1AC": "American Motors Corporation",
    "1AF": "American LaFrance",
    "1AJ": "Ajax Manufacturing trailers",
    "1AM": "Renault",
    "1BN": "Beall Trailers",
    "1B3": "Dodge",
    "1B4": "Dodge",
    "1B6": "Dodge",
    "1B7": "Dodge",
    "1B9/133": "1995",
    "1B9/274": "Brooks Brothers Trailers",
    "1B9/275": "Boydstun Metal Works trailers",
    "1B9/285": "Boss Hoss Cycles",
    "1B9/374": "Big Dog Custom",
    "1B9/975": "Motus",
    "1BA": "Blue Bird Corporation",
    "1BB": "Blue Bird Wanderlodge",
    "1BD": "Blue Bird Corporation",
    "1BL": "Balko, Inc.",
    "1C3": "Chrysler",
    "1C4": "Chrysler",
    "1C6": "Chrysler",
    "1C8": "Chrysler",
    "1C9/257": "CEI Equipment Company trailers",
    "1C9/291": "CX Automotive",
    "1C9/496": "Carlinville Truck Equipment trailers",
    "1C9/535": "Chance Coach",
    "1C9/772": "Cozad trailers",
    "1C9/971": "Cool Amphibious Manufacturers International",
    "1CM": "Checker Motors Corporation",
    "1CU": "Cushman Haulster",
    "1CY": "Crane Carrier Company",
    "1D3": "Dodge",
    "1D4": "Dodge",
    "1D7": "Dodge",
    "1D8": "Dodge",
    "1D9/008": "KME Fire Apparatus",
    "1D9/791": "Dennis Eagle, Inc.",
    "1DW": "Stoughton Trailers",
    "1E9/007": "E.D. Etnyre",
    "1E9/190": "Electric Transit Inc. trolleybus",
    "1E9/363": "Ride Industries)",
    "1E9/456": "S motorcycle",
    "1E9/526": "Epic TORQ",
    "1E9/581": "Vetter Razor",
    "1EU": "Eagle Coach Corporation",
    "1FA": "Ford",
    "1FB": "Ford",
    "1FC": "Ford",
    "1FD": "Ford",
    "1FM": "Ford",
    "1FT": "Ford",
    "1FU": "Freightliner",
    "1FV": "Freightliner",
    "1F1": "Ford",
    "1F6": "Ford",
    "1F9/037": "Federal Motors Inc.",
    "1F9/140": "Ferrara Fire Apparatus",
    "1F9/458": "Faraday Future prototypes",
    "1F9/FT1": "FWD Corp.",
    "1F9/ST1": "Seagrave Fire Apparatus",
    "1F9/ST2": "Seagrave Fire Apparatus",
    "1G": "General Motors",
    "1G0": "Opel",
    "1G1": "Chevrolet",
    "1G2": "Pontiac",
    "1G3": "Oldsmobile",
    "1G4": "Buick",
    "1G5": "GMC",
    "1G6": "Cadillac",
    "1G7": "Pontiac",
    "1G8": "Chevrolet",
    "1G9/495": "Google",
    "1GA": "Chevrolet",
    "1GB": "Chevrolet",
    "1GC": "Chevrolet",
    "1GD": "GMC",
    "1GE": "Cadillac",
    "1GF": "Flxible",
    "1GG": "Isuzu",
    "1GH": "Holden",
    "1GJ": "GMC",
    "1GK": "GMC",
    "1GM": "Pontiac",
    "1GN": "Chevrolet",
    "1GR": "Great Dane Trailers",
    "1GT": "GMC",
    "1GY": "Cadillac",
    "1HA": "Chevrolet",
    "1HD": "Harley-Davidson",
    "1HF": "Honda",
    "1HG": "Honda",
    "1HS": "International Trucks",
    "1HT": "International",
    "1HV": "IC Bus incomplete",
    "1H9/674": "Hines Specialty Vehicle",
    "1JC": "Jeep",
    "1JJ": "Wabash trailers",
    "1JT": "Jeep",
    "1JU": "Marmon Motor Company",
    "1J4": "Jeep",
    "1J7": "Jeep",
    "1J8": "Jeep",
    "1K9/058": "Kovatech Mobile Equipment fire engine",
    "1LH": "Landoll trailers",
    "1LJ": "Lincoln",
    "1LN": "Lincoln",
    "1LV": "Lectra",
    "1L0": "Lufkin Trailers",
    "1L1": "Lincoln",
    "1L9/155": "LA Exotics",
    "1L9/234": "Laforza",
    "1MB": "Mercedes-Benz",
    "1ME": "Mercury",
    "1MR": "Continental Mark VI",
    "1M0": "John Deere Gator",
    "1M1": "Mack",
    "1M2": "Mack",
    "1M3": "Mack",
    "1M4": "Mack",
    "1M8": "Motor Coach",
    "1M9/089": "Mauck Special",
    "1M9/682": "Mosler Automotive",
    "1M9/816": "2019",
    "1N4": "Nissan",
    "1N6": "Nissan",
    "1N9/019": "Neoplan USA",
    "1N9/084": "Eldorado National",
    "1N9/140": "North American Bus",
    "1N9/393": "Nikola Corporation",
    "1NK": "Kenworth",
    "1NL": "Gulf Stream Coach",
    "1NN": "Monon truck trailer",
    "1NP": "Peterbilt",
    "1NX": "Toyota",
    "1P3": "Plymouth",
    "1P4": "Plymouth MPV",
    "1P7": "Plymouth Scamp",
    "1P9/038": "Hawk Vehicles, Inc.",
    "1P9/213": "Panoz",
    "1P9/255": "Pinson Truck Equipment Company",
    "1PM": "Polar Tank Trailer",
    "1PT": "Trailmobile Trailer Corporation",
    "1PY": "John Deere USA",
    "1RF": "Roadmaster, Monaco Coach Corporation",
    "1RN": "Reitnouer",
    "1R9/956": "Reede Fabrication and Design",
    "1ST": "Airstream",
    "1S1": "Strick Trailers",
    "1S9/003": "Sutphen Corporation",
    "1S9/098": "Scania",
    "1S9/842": "Saleen S7",
    "1S9/901": "Suckerpunch Sallys, LLC",
    "1S9/944": "SSC North America",
    "1TD": "Timpte",
    "1TK": "Trail King",
    "1T7": "Thomas Built",
    "1T8": "Thomas Built",
    "1T9/717": "Thunder Mountain Custom Cycles",
    "1T9/825": "TICO Manufacturing Company",
    "1T9/899": "Tomcar USA",
    "1T9/970": "Three Two Chopper",
    "1TC": "Coachmen Recreational Vehicle Co., LLC",
    "1TU": "Transportation Manufacturing Corporation",
    "1UJ": "Jayco, Inc.",
    "1UT": "Jeep",
    "1UY": "Utility Trailer",
    "1VH": "Orion Bus",
    "1VW": "Volkswagen",
    "1V1": "Volkswagen",
    "1V2": "Volkswagen",
    "1V9/048": "Vector Aeromotive",
    "1V9/113": "speed vehicle)",
    "1V9/190": "Vanderhall Motor Works",
    "1WT": "Winnebago",
    "1WU": "White Motor Company",
    "1WV": "Winnebago",
    "1WW": "Winnebago",
    "1WX": "White Motor Company",
    "1WY": "White Motor Company",
    "1W8": "Witzco",
    "1W9/010": "It Company (truck trailer)",
    "1W9/485": "Wheego Electric",
    "1XA": "Excalibur Automobile Corporation",
    "1XK": "Kenworth",
    "1XM": "Renault",
    "1XP": "Peterbilt",
    "1Y1": "Chevrolet",
    "1YJ": "Rokon International, Inc.",
    "1YV": "Mazda",
    "1ZV": "Mazda",
    "1ZW": "Mercury",
    "1Z3": "Mitsubishi",
    "1Z7": "Mitsubishi",
    "1Z9/170": "Orange County Choppers",
    "10B": "Brenner Tank",
    "10R": "GO",
    "10T": "Oshkosh",
    "11H": "incomplete vehicle)",
    "12A": "Avanti",
    "137": "AM General Hummer",
    "13N": "Fontaine",
    "15G": "Gillig",
    "16C": "Clenet Coachworks",
    "16X": "Vixen 21 motorhome",
    "17N": "John Deere",
    "19U": "Honda",
    "19V": "Honda",
    "19X": "Honda",
    "2A3": "Imperial",
    "2A4": "Chrysler",
    "2A8": "Chrysler",
    "2AY": "Hino",
    "2AZ": "Hino",
    "2BC": "Jeep",
    "2BP": "Doo",
    "2BV": "Can-Am",
    "2BW": "Can-Am",
    "2BX": "Can-Am",
    "2BZ": "Can-Am",
    "3B6": "Dodge",
    "3B7": "Dodge",
    "3C3": "Chrysler",
    "3C3": "Chrysler",
    "3C4": "Chrysler",
    "3C4": "Chrysler",
    "3C6": "Chrysler",
    "3C7": "Chrysler",
    "3C8": "Chrysler",
    "3CE": "Volvo",
    "3CG": "KTMMEX S.A. de C.V.",
    "3CZ": "Honda",
    "3D2": "Dodge",
    "3D3": "Dodge",
    "3D4": "Dodge",
    "3D6": "Dodge",
    "3D7": "Dodge",
    "3EL": "ATRO",
    "3E4": "Fiat",
    "3FA": "Ford",
    "3FC": "Ford",
    "3FE": "Ford",
    "3FM": "Ford",
    "3FN": "Ford",
    "3FR": "Ford",
    "3FT": "Ford",
    "3F6": "Sterling",
    "3G": "General Motors",
    "3G0": "Holden",
    "3G1": "Chevrolet",
    "3G2": "Pontiac",
    "3G4": "Buick",
    "3G5": "Buick",
    "3G7": "Pontiac",
    "3GC": "Chevrolet",
    "3GK": "GMC",
    "3GM": "Holden",
    "3GN": "Chevrolet",
    "3GP": "Honda",
    "3GS": "Saturn",
    "3GT": "GMC",
    "3GY": "Cadillac",
    "3H1": "Honda",
    "3H3": "Hyundai",
    "3HA": "International Trucks",
    "3HC": "International Trucks",
    "3HD": "Honda",
    "3HG": "Honda",
    "3HS": "International Trucks",
    "3HT": "International Trucks",
    "3HV": "International incomplete",
    "3JB": "Can-Am",
    "3KM": "Hyundai",
    "3KP": "Hyundai",
    "3LN": "Lincoln",
    "3MA": "Mercury",
    "3MD": "Mazda",
    "3ME": "Mercury",
    "3MF": "BMW",
    "3MJ": "Mazda",
    "3MV": "Mazda",
    "3MW": "BMW",
    "3MY": "Toyota",
    "3MZ": "Mazda",
    "3N1": "Nissan",
    "3N6": "Chevrolet",
    "3N8": "Nissan",
    "3NS": "Polaris Industries ATV",
    "3NE": "Polaris Industries UTV",
    "3P3": "Plymouth",
    "3PC": "Infiniti",
    "3TM": "Toyota",
    "3TY": "Toyota",
    "3VV": "Volkswagen",
    "3VW": "Volkswagen",
    "3WK": "Kenworth",
    "3WP": "Peterbilt",
    "4A3": "Mitsubishi",
    "4A4": "Mitsubishi",
    "4B3": "Dodge",
    "4B9/038": "BYD",
    "4C3": "Chrysler",
    "4C6": "Reinke Manufacturing Company",
    "4C9/272": "Christini Technologies",
    "4C9/561": "Czinger",
    "4C9/626": "Canoo Inc.",
    "4CD": "Oshkosh",
    "4DR": "IC",
    "4E3": "Star Motors factory",
    "4EN": "truck)",
    "4F2": "Mazda",
    "4F4": "Mazda",
    "4G1": "Chevrolet",
    "4G2": "Pontiac",
    "4G3": "Toyota",
    "4G5": "General Motors",
    "4GD": "Opel",
    "4GL": "Buick",
    "4GT": "Isuzu",
    "4JG": "Mercedes-Benz",
    "4J8": "LBT, Inc.",
    "4KB": "Chevrolet",
    "4KD": "GMC",
    "4KE": "U.S. Electricar Consulier",
    "4KL": "Isuzu",
    "4LM": "Capacity of Texas",
    "4M2": "Mercury",
    "4MB": "Mitsubishi",
    "4ML": "Oshkosh",
    "4MZ": "Buell Motorcycle Company",
    "4N2": "Nissan",
    "4NU": "Isuzu",
    "4P1": "Pierce Manufacturing Inc. USA",
    "4P3": "Mitsubishi",
    "4RK": "Nova Bus",
    "4S1": "Subaru",
    "4S2": "Subaru",
    "4S3": "Subaru",
    "4S4": "Subaru",
    "4S6": "Subaru",
    "4S7": "Spartan Motors",
    "4S9/197": "Smith Electric",
    "4S9/345": "Satellite Suites",
    "4S9/419": "Spartan Motors",
    "4S9/454": "Scuderia Cameron Glickenhaus",
    "4S9/520": "Signature Autosport, LLC",
    "4S9/542": "Scuderia Cameron Glickenhaus SCG Boot",
    "4S9/544": "Scuderia Cameron Glickenhaus",
    "4S9/559": "Spartan Fire, LLC",
    "4S9/560": "Spartan Fire, LLC",
    "4S9/569": "SC Autosports, LLC",
    "4TA": "Toyota",
    "4T1": "Toyota",
    "4T3": "Toyota",
    "4T4": "Toyota",
    "4T9/208": "Xos, Inc.",
    "4T9/228": "Lumen",
    "4UF": "Arctic Cat Inc.",
    "4US": "BMW",
    "4UZ": "Freightliner",
    "4V0": "Crossroads RV",
    "4V1": "WhiteGMC",
    "4V2": "WhiteGMC",
    "4V3": "Volvo",
    "4V4": "Volvo",
    "4V5": "Volvo",
    "4V6": "Volvo",
    "4VA": "Volvo",
    "4VE": "Volvo",
    "4VG": "Volvo",
    "4VH": "Volvo",
    "4VM": "Volvo",
    "4VZ": "Spartan Motors",
    "4WW": "Wilson Trailer Sales",
    "4W1": "Chevrolet",
    "4W5": "Acura",
    "4XA": "Polaris Inc.",
    "4X4": "Forest River",
    "4YD": "KeyStone RV Company",
    "4YM": "Carry-On Trailer, Inc.",
    "4Z3": "American LaFrance",
    "43C": "Consulier",
    "44K": "incomplete vehicle)",
    "46G": "Gillig",
    "46J": "Federal Motors Inc",
    "478": "Honda",
    "480": "Sterling",
    "49H": "Sterling",
    "5AS": "2011",
    "5AX": "Armor",
    "5A4": "Load Rite Trailers Inc.",
    "5BP": "Solectria",
    "5BZ": "Nissan",
    "5B4": "Workhorse Custom Chassis, LLC",
    "5CD": "Indian Motorcycle Company of America",
    "5CX": "Shelby Series 1",
    "5DF": "Thomas Dennis Company LLC",
    "5DG": "Terex Advance Mixer",
    "5EH": "Henderson Motorcycle",
    "5EO": "Cottrell",
    "5FC": "speed vehicles)",
    "5FN": "Honda",
    "5FP": "Honda",
    "5FR": "Honda",
    "5FT": "Feeling Trailers",
    "5FY": "New Flyer",
    "5GA": "Buick",
    "5GD": "Daewoo",
    "5GN": "Hummer H3T",
    "5GR": "Hummer H2",
    "5GT": "Hummer H3",
    "5GZ": "Saturn",
    "5G8": "Holden",
    "5HD": "Harley-Davidson",
    "5HT": "Heil Trailer",
    "5J5": "Club",
    "5J6": "Honda",
    "5J8": "Honda",
    "5KB": "Honda",
    "5KJ": "Western Star",
    "5KK": "Western Star",
    "5KM": "Vento",
    "5KT": "Karavan Trailers",
    "5L1": "Lincoln",
    "5L5": "American IronHorse",
    "5LD": "Lincoln",
    "5LM": "Lincoln",
    "5LT": "Lincoln",
    "5MZ": "Buell Motorcycle Company for export markets",
    "5N1": "Infiniti",
    "5N3": "Infiniti",
    "5NH": "Forest River",
    "5NM": "Hyundai",
    "5NP": "Hyundai",
    "5NT": "Hyundai",
    "5PV": "Hino",
    "5RJ": "Android Industries LLC",
    "5RX": "Heartland Recreational",
    "5S3": "7X",
    "5SA": "Suzuki",
    "5SX": "American LaFrance",
    "5TB": "Toyota",
    "5TD": "Toyota",
    "5TE": "Toyota",
    "5TF": "Toyota",
    "5TU": "Construction Trailer Specialist",
    "5UM": "BMW",
    "5UX": "BMW",
    "5VC": "Autocar",
    "5VF": "speed vehicle)",
    "5VP": "Victory",
    "5V8": "Vanguard National",
    "5WE": "IC Bus",
    "5XX": "Kia",
    "5XY": "Hyundai",
    "5YA": "Indian Motorcycle Company",
    "5YF": "Toyota",
    "5YJ": "Tesla",
    "5YM": "BMW",
    "5YN": "Cruise Car, Inc.",
    "5Y2": "Pontiac",
    "5Y4": "Yamaha",
    "5ZT": "Forest River",
    "5ZU": "Greenkraft",
    "5Z6": "Nissan",
    "50E": "Lucid Motors",
    "50G": "Karma Automotive",
    "516": "Autocar",
    "51R": "Brammo",
    "522": "speed vehicle)",
    "523": "VPG",
    "52C": "GEM subsidiary of Polaris Inc.",
    "537": "Azure Dynamics Transit Connect Electric",
    "538": "Zero",
    "53G": "Coda Automotive",
    "53T": "Think North America in Elkhart, IN",
    "546": "EBR",
    "54C": "Winnebago Industries travel trailer",
    "54D": "Chevrolet",
    "54F": "Rosenbauer",
    "55S": "Mercedes-Benz",
    "56K": "Indian Motorcycle International, LLC",
    "573": "Grand Design RV",
    "57C": "Maurer",
    "57R": "Oreion",
    "57S": "Lightning Motors Corp.",
    "57W": "Mobility Ventures",
    "57X": "Polaris Slingshot",
    "58A": "Lexus",
    "6AB": "MAN",
    "6AM": "Jayco Corp.",
    "6F1": "Ford",
    "6F2": "Iveco",
    "6F4": "Nissan",
    "6F5": "Kenworth",
    "6FM": "Mack",
    "6FP": "Ford",
    "6G1": "General Motors",
    "6G2": "Pontiac",
    "6G3": "General Motors",
    "6H8": "General Motors",
    "6KT": "BCI",
    "6MM": "Mitsubishi",
    "6MP": "Mercury",
    "6T1": "Toyota",
    "6U9": "Privately Imported car in Australia",
    "7AB": "MAN",
    "7AT": "VIN assigned by New Zealand Transport Authority Waka Kotahi from 29 Nov 2009",
    "7A1": "Mitsubishi",
    "7A3": "Honda",
    "7A4": "Toyota",
}
