"""add waranty date

Revision ID: 100fc7089118
Revises: a06a9d609010
Create Date: 2024-12-05 17:24:47.935597

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "100fc7089118"
down_revision = "a06a9d609010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_data",
        sa.Column("consumption", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column("vehicle_model", sa.Column("warranty_date", sa.Date(), nullable=True))
    op.add_column(
        "vehicle_model",
        sa.Column("warranty_km", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_column("vehicle_model", "warranty_km")
    op.drop_column("vehicle_model", "warranty_date")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_column("vehicle_data", "consumption")
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

