"""add vin into vehicle

Revision ID: 108b431c5133
Revises: cfc770ee5c62
Create Date: 2024-11-10 16:58:40.357394

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "108b431c5133"
down_revision = "cfc770ee5c62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.add_column("vehicle", sa.Column("vin", sa.String(length=50), nullable=True))
    op.create_table_comment("vehicle", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("vehicle", existing_comment="", schema=None)
    op.drop_column("vehicle", "vin")
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

