"""adding language for flash reports

Revision ID: 13e03e674ef3
Revises: 4c1994ec12e8
Create Date: 2025-11-06 15:42:06.540497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e03e674ef3'
down_revision = '4c1994ec12e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE language_enum AS ENUM ('FR', 'EN')")
    op.execute("ALTER TABLE flash_report_combination ADD COLUMN language language_enum NOT NULL DEFAULT 'EN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE flash_report_combination DROP COLUMN language")
    op.execute("DROP TYPE language_enum")
    # ### end Alembic commands ###

