"""changing battery structure

Revision ID: 1937f6313ac4
Revises: 7df6e9ff07f7
Create Date: 2025-01-28 09:12:03.722475

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1937f6313ac4"
down_revision = "7df6e9ff07f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_model", "battery_id")
    op.drop_table("battery")
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_model", sa.Column("battery_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "vehicle_model", sa.Column("source", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "vehicle_model",
        sa.Column("battery_chemistry", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "vehicle_model", sa.Column("battery_oem", sa.String(length=100), nullable=True)
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model",
        sa.Column("battery_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_column("vehicle_model", "battery_oem")
    op.drop_column("vehicle_model", "battery_chemistry")
    op.drop_column("vehicle_model", "source")
    op.drop_column("vehicle_model", "battery_name")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.create_table(
        "battery",
        sa.Column(
            "battery_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "battery_oem", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "battery_chemistry",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "battery_reference",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id", name="battery_pkey"),
    )
    # ### end Alembic commands ###
