"""improve createdat updatedat

Revision ID: 202512191515
Revises: 202512191035
Create Date: 2025-12-19 16:15:48.217159

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "202512191515"
down_revision = "202512191035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_aggregate")
    op.drop_table("fleet_aggregate")
    op.drop_table("regional_aggregate")
    op.drop_column("company", "updated_at")
    op.drop_column("flash_report_combination", "updated_at")
    op.drop_column("fleet", "updated_at")
    op.drop_column("make", "updated_at")
    op.drop_column("region", "updated_at")
    op.drop_column("role", "updated_at")
    op.drop_column("user_fleet", "updated_at")

    # Create a reusable function to update updated_at column automatically
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Get connection to query for tables with updated_at columns
    conn = op.get_bind()

    # Query to find all tables with updated_at columns
    result = conn.execute(
        sa.text("""
        SELECT table_name, table_schema
        FROM information_schema.columns
        WHERE column_name = 'updated_at'
        AND table_schema NOT IN ('information_schema', 'pg_catalog', 'pg_toast')
        ORDER BY table_schema, table_name;
    """)
    )

    tables = result.fetchall()

    # Create triggers for each table
    for table_name, table_schema in tables:
        # Normalize schema (handle None or empty string)
        schema = table_schema or "public"

        # Build the full table identifier
        if schema != "public":
            full_table_name = f'"{schema}"."{table_name}"'
            trigger_name = f"update_{schema}_{table_name}_updated_at"
        else:
            full_table_name = f'"{table_name}"'
            trigger_name = f"update_{table_name}_updated_at"

        # Sanitize trigger name (PostgreSQL identifiers can be up to 63 chars)
        # Replace any problematic characters and truncate if needed
        trigger_name = trigger_name.replace("-", "_").replace(".", "_")
        if len(trigger_name) > 63:
            trigger_name = trigger_name[:63]

        # Create trigger (using IF NOT EXISTS equivalent by dropping first if exists)
        op.execute(f"""
            DROP TRIGGER IF EXISTS "{trigger_name}" ON {full_table_name};
        """)
        op.execute(f"""
            CREATE TRIGGER "{trigger_name}"
            BEFORE UPDATE ON {full_table_name}
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_fleet",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "region",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "make",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "fleet",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "flash_report_combination",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )
    op.add_column(
        "company",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
    )

    op.create_table(
        "regional_aggregate",
        sa.Column("region_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_soh",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_soc",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_temperature",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_voltage",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "energy_consumption",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["region.id"], name=op.f("regional_aggregate_region_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("regional_aggregate_pkey")),
    )
    op.create_table(
        "fleet_aggregate",
        sa.Column("fleet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_soh",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_value",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_energy_consumption",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"], ["fleet.id"], name=op.f("fleet_aggregate_fleet_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("fleet_aggregate_pkey")),
    )
    op.create_table(
        "vehicle_aggregate",
        sa.Column("vehicle_model_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "avg_soh",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "energy_consumption",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
            name=op.f("vehicle_aggregate_vehicle_model_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("vehicle_aggregate_pkey")),
    )

    # Removing the triggers for the updated_at column
    # Get connection to query for tables with updated_at columns to drop the triggers
    conn = op.get_bind()

    # Query to find all tables with updated_at columns
    result = conn.execute(
        sa.text("""
        SELECT table_name, table_schema
        FROM information_schema.columns
        WHERE column_name = 'updated_at'
        AND table_schema NOT IN ('information_schema', 'pg_catalog', 'pg_toast')
        ORDER BY table_schema, table_name;
    """)
    )

    tables = result.fetchall()

    # Drop triggers for each table
    for table_name, table_schema in tables:
        # Normalize schema (handle None or empty string)
        schema = table_schema or "public"

        # Build the full table identifier
        if schema != "public":
            full_table_name = f'"{schema}"."{table_name}"'
            trigger_name = f"update_{schema}_{table_name}_updated_at"
        else:
            full_table_name = f'"{table_name}"'
            trigger_name = f"update_{table_name}_updated_at"

        # Sanitize trigger name (PostgreSQL identifiers can be up to 63 chars)
        trigger_name = trigger_name.replace("-", "_").replace(".", "_")
        if len(trigger_name) > 63:
            trigger_name = trigger_name[:63]

        # Drop trigger
        op.execute(f"""
            DROP TRIGGER IF EXISTS "{trigger_name}" ON {full_table_name};
        """)

    # Drop the function
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    # ### end Alembic commands ###
