"""creation de la table vehicle status

Revision ID: 202512041647
Revises: 202512011300
Create Date: 2025-12-04 17:47:04.700482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512041647"
down_revision = "202512030810"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_status",
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("vin", sa.String(length=50), nullable=False),
        sa.Column("status_name", sa.String(length=100), nullable=False),
        sa.Column("status_value", sa.Boolean(), nullable=False),
        sa.Column("process_step", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_status")
    # ### end Alembic commands ###
