"""ajout colonne timestamp_last_data_collected

Revision ID: 202512111326
Revises: 202512111009
Create Date: 2025-12-11 14:26:10.078030

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512111326"
down_revision = "202512111009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_data",
        sa.Column("timestamp_last_data_collected", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_data", "timestamp_last_data_collected")
    # ### end Alembic commands ###
