"""Ajout de data points dans table Vehicle Model

Revision ID: 202512011300
Revises: 202511271319
Create Date: 2025-12-01 14:00:13.204572

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512011300"
down_revision = "202512011006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model", sa.Column("maximum_speed", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model",
        sa.Column("charge_plug_location", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "vehicle_model",
        sa.Column("charge_plug_type", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "vehicle_model", sa.Column("fast_charge_max_power", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model", sa.Column("fast_charge_duration", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model",
        sa.Column("standard_charge_duration", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vehicle_model", sa.Column("ac_charge_duration", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model", sa.Column("autonomy_city_winter", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model", sa.Column("autonomy_city_summer", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vehicle_model",
        sa.Column("autonomy_highway_winter", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vehicle_model",
        sa.Column("autonomy_highway_summer", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vehicle_model",
        sa.Column("autonomy_combined_winter", sa.Integer(), nullable=True),
    )
    op.add_column(
        "vehicle_model",
        sa.Column("autonomy_combined_summer", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_model", "autonomy_combined_summer")
    op.drop_column("vehicle_model", "autonomy_combined_winter")
    op.drop_column("vehicle_model", "autonomy_highway_summer")
    op.drop_column("vehicle_model", "autonomy_highway_winter")
    op.drop_column("vehicle_model", "autonomy_city_summer")
    op.drop_column("vehicle_model", "autonomy_city_winter")
    op.drop_column("vehicle_model", "ac_charge_duration")
    op.drop_column("vehicle_model", "standard_charge_duration")
    op.drop_column("vehicle_model", "fast_charge_duration")
    op.drop_column("vehicle_model", "fast_charge_max_power")
    op.drop_column("vehicle_model", "charge_plug_type")
    op.drop_column("vehicle_model", "charge_plug_location")
    op.drop_column("vehicle_model", "maximum_speed")
    # ### end Alembic commands ###
