"""Reforme de la table battery

Revision ID: 202512030810
Revises: 202512011006
Create Date: 2025-12-03 09:10:26.686377

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512030810"
down_revision = "202512011300"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "battery", sa.Column("battery_type", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "battery", sa.Column("estimated_capacity", sa.String(length=100), nullable=True)
    )
    op.add_column("battery", sa.Column("battery_modules", sa.Integer(), nullable=True))
    op.add_column(
        "battery", sa.Column("battery_cells", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "battery",
        sa.Column("battery_weight", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "battery",
        sa.Column("battery_architecture", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "battery", sa.Column("battery_tms", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "battery",
        sa.Column(
            "battery_voltage_nominal", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "battery", sa.Column("battery_warranty_period", sa.Integer(), nullable=True)
    )
    op.add_column(
        "battery",
        sa.Column(
            "battery_warranty_mileage", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.drop_column("battery", "battery_name")
    op.drop_column("battery", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "battery",
        sa.Column("source", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "battery",
        sa.Column(
            "battery_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("battery", "battery_warranty_mileage")
    op.drop_column("battery", "battery_warranty_period")
    op.drop_column("battery", "battery_voltage_nominal")
    op.drop_column("battery", "battery_tms")
    op.drop_column("battery", "battery_architecture")
    op.drop_column("battery", "battery_weight")
    op.drop_column("battery", "battery_cells")
    op.drop_column("battery", "battery_modules")
    op.drop_column("battery", "estimated_capacity")
    op.drop_column("battery", "battery_type")
    # ### end Alembic commands ###
