"""ajout colonne bib_score a vehicle

Revision ID: 202512151003
Revises: 202512111009
Create Date: 2025-12-15 11:03:30.005016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202512151003'
down_revision = '202512111009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('bib_score', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'bib_score')
    # ### end Alembic commands ###

