"""Ajout de la table premium_report

Revision ID: 202511271319
Revises: 202511181516
Create Date: 2025-11-27 14:19:27.204134

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202511271319"
down_revision = "202511181516"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "premium_report",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("report_url", sa.String(length=2000), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("premium_report")
    # ### end Alembic commands ###
