"""Ajout de l'ID d'evdatabase à vehicle_model

Revision ID: 202511181516
Revises: 202511071733
Create Date: 2025-11-14 16:16:18.023563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202511181516"
down_revision = "202511172306"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model",
        sa.Column("evdb_model_id", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_model", "evdb_model_id")
    # ### end Alembic commands ###
