"""Retrait colonne last data date

Revision ID: 202512101558
Revises: 202512041647
Create Date: 2025-12-10 16:58:53.540611

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512101558"
down_revision = "202512041647"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "last_date_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle",
        sa.Column("last_date_data", sa.DATE(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
