"""ajout colonne autonomy

Revision ID: 202512111009
Revises: 202512101558
Create Date: 2025-12-11 11:09:26.042990

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512111009"
down_revision = "202512101558"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_data",
        sa.Column("real_autonomy", sa.Numeric(precision=10, scale=0), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_data", "real_autonomy")
    # ### end Alembic commands ###
