"""flash report logging nullable

Revision ID: 202512011006
Revises: 202512010934
Create Date: 2025-12-01 11:06:29.455003

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512011006"
down_revision = "202511271319"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flash_report_combination", "token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(
        op.f("flash_report_combination_token_key"),
        "flash_report_combination",
        type_="unique",
    )
    op.alter_column(
        "flash_report_combination", "model", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "flash_report_combination", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "flash_report_combination",
        "odometer",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flash_report_combination", "token", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(
        op.f("flash_report_combination_token_key"),
        "flash_report_combination",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "flash_report_combination",
        "odometer",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "flash_report_combination", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "flash_report_combination", "model", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
