"""Ajout table fleet tesla atuhentication code

Revision ID: 202512181452
Revises: 202512151003
Create Date: 2025-12-18 15:52:48.419103

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202512181452"
down_revision = "202512151003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "fleet_tesla_authentication_code",
        sa.Column("fleet_id", sa.UUID(), nullable=False),
        sa.Column("authentication_code", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier of the row",
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fleet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table("fleet_tesla_authentication_code")
    # ### end Alembic commands ###
