"""ajout colonne real_autonomy a vehicle_model

Revision ID: 202601141000
Revises: 202601131700
Create Date: 2026-01-14 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202601141000"
down_revision = "202601131700"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "vehicle_model",
        sa.Column(
            "real_autonomy",
            sa.Integer(),
            nullable=True,
            comment="Autonomy calculated by Bib",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_model", "real_autonomy")
    # ### end Alembic commands ###
