"""Ajout pour refonte activation

Revision ID: 202601061543
Revises: 202601061021
Create Date: 2026-01-06 16:43:31.189444

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202601061543"
down_revision = "202601061021"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_activation_history",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("activation_requested_status", sa.Boolean(), nullable=False),
        sa.Column("activation_status", sa.Boolean(), nullable=False),
        sa.Column("activation_status_message", sa.String(length=255), nullable=False),
        sa.Column("oem_detail", sa.String(length=555), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="Auto-incrementing identifier of the row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "vehicle", sa.Column("activation_requested_status", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "vehicle", sa.Column("activation_start_date", sa.Date(), nullable=True)
    )
    op.add_column("vehicle", sa.Column("activation_end_date", sa.Date(), nullable=True))
    op.add_column(
        "vehicle",
        sa.Column("activation_status_message", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "vehicle", sa.Column("activation_comment", sa.String(length=255), nullable=True)
    )
    op.add_column("vehicle", sa.Column("is_processed", sa.Boolean(), nullable=True))
    op.alter_column(
        "vehicle", "vehicle_model_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicle", "vehicle_model_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("vehicle", "is_processed")
    op.drop_column("vehicle", "activation_comment")
    op.drop_column("vehicle", "activation_status_message")
    op.drop_column("vehicle", "activation_end_date")
    op.drop_column("vehicle", "activation_start_date")
    op.drop_column("vehicle", "activation_requested_status")
    op.drop_table("vehicle_activation_history")
    # ### end Alembic commands ###
