"""create flash_report_combination table

Revision ID: 21fc3d4b3526
Revises: 74a7ad99bd0c
Create Date: 2025-10-15 14:50:37.385986

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21fc3d4b3526"
down_revision = "74a7ad99bd0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flash_report_combination",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column("make", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("odometer", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flash_report_combination")
    # ### end Alembic commands ###

