"""adding_vin_to_flash_report-table

Revision ID: 2f43708472d4
Revises: 21fc3d4b3526
Create Date: 2025-10-20 14:28:57.747788

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2f43708472d4"
down_revision = "21fc3d4b3526"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flash_report_combination", sa.Column("vin", sa.String(), nullable=False)
    )
    op.alter_column(
        "flash_report_combination",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Date of the last update to this row",
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "flash_report_combination",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Date of creation of this row",
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flash_report_combination",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Date of creation of this row",
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "flash_report_combination",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Date of the last update to this row",
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("flash_report_combination", "vin")
    # ### end Alembic commands ###

