"""Retrait colonne is_displayed

Revision ID: 4f6166e46805
Revises: 21fc3d4b3526
Create Date: 2025-10-23 15:42:18.663206

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f6166e46805"
down_revision = "21fc3d4b3526"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "is_displayed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle",
        sa.Column("is_displayed", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###

