"""maj

Revision ID: 54542c586857
Revises: 939ec95511f2
Create Date: 2025-03-04 11:06:31.266010

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54542c586857"
down_revision = "939ec95511f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        comment="Unique identifier of the row",
        existing_nullable=False,
        schema="tesla",
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date of the last update to this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date of creation of this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user_tokens",
        "id",
        existing_type=sa.UUID(),
        comment="Unique identifier of the row",
        existing_nullable=False,
        schema="tesla",
    )
    op.alter_column(
        "user_tokens",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date of the last update to this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Date of creation of this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date of creation of this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user_tokens",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date of the last update to this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user_tokens",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique identifier of the row",
        existing_nullable=False,
        schema="tesla",
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date of creation of this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Date of the last update to this row",
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        schema="tesla",
    )
    op.alter_column(
        "user",
        "id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique identifier of the row",
        existing_nullable=False,
        schema="tesla",
    )
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

