"""add api external

Revision ID: 6628203e2a2a
Revises: 67449a23ef8c
Create Date: 2025-03-26 11:03:35.605416

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6628203e2a2a"
down_revision = "67449a23ef8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table(
        "api_pricing_plan",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "requests_limit",
            sa.Integer(),
            nullable=False,
            comment="Limite quotidienne de requêtes API",
        ),
        sa.Column(
            "max_distinct_vins",
            sa.Integer(),
            nullable=False,
            comment="Nombre maximal de VINs distincts autorisés par jour",
        ),
        sa.Column(
            "price_per_request",
            sa.Numeric(precision=10, scale=4),
            nullable=False,
            comment="Prix par requête en euros",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "api_user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("api_key", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_index("ix_api_user_api_key", "api_user", ["api_key"], unique=False)
    op.create_index("ix_api_user_user_id", "api_user", ["user_id"], unique=False)
    op.create_table(
        "api_billing",
        sa.Column("api_user_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("distinct_vins", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=True),
        sa.Column("paid", sa.Boolean(), nullable=True),
        sa.Column("payment_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.ForeignKeyConstraint(
            ["api_user_id"],
            ["api_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_billing_api_user_id", "api_billing", ["api_user_id"], unique=False
    )
    op.create_index("ix_api_billing_paid", "api_billing", ["paid"], unique=False)
    op.create_index(
        "ix_api_billing_period",
        "api_billing",
        ["period_start", "period_end"],
        unique=False,
    )
    op.create_table(
        "api_call_log",
        sa.Column("api_user_id", sa.UUID(), nullable=False),
        sa.Column("vin", sa.String(length=50), nullable=False),
        sa.Column(
            "endpoint",
            sa.String(length=100),
            nullable=False,
            comment="Point d'accès appelé (ex: /vehicle/static)",
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "response_time",
            sa.Float(),
            nullable=True,
            comment="Temps de réponse en millisecondes",
        ),
        sa.Column(
            "status_code",
            sa.Integer(),
            nullable=True,
            comment="Code de statut HTTP de la réponse",
        ),
        sa.Column("is_billed", sa.Boolean(), nullable=False),
        sa.Column("billed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["api_user_id"],
            ["api_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_call_log_api_user_id", "api_call_log", ["api_user_id"], unique=False
    )
    op.create_index(
        "ix_api_call_log_is_billed", "api_call_log", ["is_billed"], unique=False
    )
    op.create_index(
        "ix_api_call_log_timestamp", "api_call_log", ["timestamp"], unique=False
    )
    op.create_index("ix_api_call_log_vin", "api_call_log", ["vin"], unique=False)
    op.create_table(
        "api_user_pricing",
        sa.Column("api_user_id", sa.UUID(), nullable=False),
        sa.Column("pricing_plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "custom_requests_limit",
            sa.Integer(),
            nullable=True,
            comment="Limite personnalisée qui remplace celle du plan si définie",
        ),
        sa.Column(
            "custom_max_distinct_vins",
            sa.Integer(),
            nullable=True,
            comment="Limite de VINs distincts personnalisée qui remplace celle du plan si définie",
        ),
        sa.Column(
            "custom_price_per_request",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Prix personnalisé qui remplace celui du plan si défini",
        ),
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=False,
            comment="Date d'entrée en vigueur de ce plan pour cet utilisateur",
        ),
        sa.Column(
            "expiration_date",
            sa.Date(),
            nullable=True,
            comment="Date d'expiration si applicable",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.ForeignKeyConstraint(
            ["api_user_id"],
            ["api_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pricing_plan_id"],
            ["api_pricing_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_user_pricing_api_user_id",
        "api_user_pricing",
        ["api_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_api_user_pricing_pricing_plan_id",
        "api_user_pricing",
        ["pricing_plan_id"],
        unique=False,
    )
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.drop_index("ix_api_user_pricing_pricing_plan_id", table_name="api_user_pricing")
    op.drop_index("ix_api_user_pricing_api_user_id", table_name="api_user_pricing")
    op.drop_table("api_user_pricing")
    op.drop_index("ix_api_call_log_vin", table_name="api_call_log")
    op.drop_index("ix_api_call_log_timestamp", table_name="api_call_log")
    op.drop_index("ix_api_call_log_is_billed", table_name="api_call_log")
    op.drop_index("ix_api_call_log_api_user_id", table_name="api_call_log")
    op.drop_table("api_call_log")
    op.drop_index("ix_api_billing_period", table_name="api_billing")
    op.drop_index("ix_api_billing_paid", table_name="api_billing")
    op.drop_index("ix_api_billing_api_user_id", table_name="api_billing")
    op.drop_table("api_billing")
    op.drop_index("ix_api_user_user_id", table_name="api_user")
    op.drop_index("ix_api_user_api_key", table_name="api_user")
    op.drop_table("api_user")
    op.drop_table("api_pricing_plan")
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

