"""soh_comparison fix

Revision ID: 67449a23ef8c
Revises: e78f051b68c7
Create Date: 2025-03-13 09:56:51.891663

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "67449a23ef8c"
down_revision = "e78f051b68c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.alter_column(
        "vehicle_data",
        "soh_comparison",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=sa.Numeric(precision=6, scale=3),
        existing_nullable=True,
    )
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_data",
        "soh_comparison",
        existing_type=sa.Numeric(precision=6, scale=3),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=True,
    )
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

