"""add index

Revision ID: 6c12932e6c17
Revises: 208124326b98
Create Date: 2024-11-20 22:23:45.185702

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c12932e6c17"
down_revision = "208124326b98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_index("ix_vehicle_fleet_id", "vehicle", ["fleet_id"], unique=False)
    op.create_index(
        "ix_vehicle_model_id", "vehicle", ["vehicle_model_id"], unique=False
    )
    op.create_index("ix_vehicle_region_id", "vehicle", ["region_id"], unique=False)
    op.create_index("ix_vehicle_vin", "vehicle", ["vin"], unique=False)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_index("ix_vehicle_vin", table_name="vehicle")
    op.drop_index("ix_vehicle_region_id", table_name="vehicle")
    op.drop_index("ix_vehicle_model_id", table_name="vehicle")
    op.drop_index("ix_vehicle_fleet_id", table_name="vehicle")
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

