"""trednline bool

Revision ID: 6e3542ad0480
Revises: 62cd0bf4aad1
Create Date: 2025-05-19 18:37:59.966878

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e3542ad0480"
down_revision = "62cd0bf4aad1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table_comment("api_pricing_plan", "", existing_comment=None, schema=None)
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_model", sa.Column("trendline_version", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "vehicle_model", sa.Column("trendline_model", sa.Boolean(), nullable=True)
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    op.drop_column("vehicle_model", "trendline_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model",
        sa.Column("trendline_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_column("vehicle_model", "trendline_model")
    op.drop_column("vehicle_model", "trendline_version")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.drop_table_comment("api_pricing_plan", existing_comment="", schema=None)
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

