"""dleeting api_user

Revision ID: 6f6c64e66560
Revises: b6d0cc33c7db
Create Date: 2025-05-27 17:00:18.477596

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f6c64e66560"
down_revision = "b6d0cc33c7db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.add_column("api_billing", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index("ix_api_billing_api_user_id", table_name="api_billing")
    op.create_index("ix_api_billing_user_id", "api_billing", ["user_id"], unique=False)
    op.drop_constraint(
        "api_billing_api_user_id_fkey", "api_billing", type_="foreignkey"
    )
    op.create_foreign_key(None, "api_billing", "user", ["user_id"], ["id"])
    op.drop_column("api_billing", "api_user_id")
    op.add_column("api_call_log", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index("ix_api_call_log_api_user_id", table_name="api_call_log")
    op.create_index(
        "ix_api_call_log_user_id", "api_call_log", ["user_id"], unique=False
    )
    op.drop_constraint(
        "api_call_log_api_user_id_fkey", "api_call_log", type_="foreignkey"
    )
    op.create_foreign_key(None, "api_call_log", "user", ["user_id"], ["id"])
    op.drop_column("api_call_log", "api_user_id")
    op.create_table_comment("api_pricing_plan", "", existing_comment=None, schema=None)
    op.drop_index("ix_api_user_pricing_api_user_id", table_name="api_user_pricing")
    op.drop_index("ix_api_user_pricing_pricing_plan_id", table_name="api_user_pricing")
    op.create_index(
        "ix_user_pricing_pricing_plan_id",
        "api_user_pricing",
        ["pricing_plan_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_pricing_user_id", "api_user_pricing", ["user_id"], unique=False
    )
    op.drop_constraint(
        "api_user_pricing_api_user_id_fkey", "api_user_pricing", type_="foreignkey"
    )
    op.drop_column("api_user_pricing", "api_user_id")
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.add_column(
        "api_user_pricing",
        sa.Column("api_user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "api_user_pricing_api_user_id_fkey",
        "api_user_pricing",
        "api_user",
        ["api_user_id"],
        ["id"],
    )
    op.drop_index("ix_user_pricing_user_id", table_name="api_user_pricing")
    op.drop_index("ix_user_pricing_pricing_plan_id", table_name="api_user_pricing")
    op.create_index(
        "ix_api_user_pricing_pricing_plan_id",
        "api_user_pricing",
        ["pricing_plan_id"],
        unique=False,
    )
    op.create_index(
        "ix_api_user_pricing_api_user_id",
        "api_user_pricing",
        ["api_user_id"],
        unique=False,
    )
    op.drop_table_comment("api_pricing_plan", existing_comment="", schema=None)
    op.add_column(
        "api_call_log",
        sa.Column("api_user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "api_call_log", type_="foreignkey")
    op.create_foreign_key(
        "api_call_log_api_user_id_fkey",
        "api_call_log",
        "api_user",
        ["api_user_id"],
        ["id"],
    )
    op.drop_index("ix_api_call_log_user_id", table_name="api_call_log")
    op.create_index(
        "ix_api_call_log_api_user_id", "api_call_log", ["api_user_id"], unique=False
    )
    op.drop_column("api_call_log", "user_id")
    op.add_column(
        "api_billing",
        sa.Column("api_user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "api_billing", type_="foreignkey")
    op.create_foreign_key(
        "api_billing_api_user_id_fkey",
        "api_billing",
        "api_user",
        ["api_user_id"],
        ["id"],
    )
    op.drop_index("ix_api_billing_user_id", table_name="api_billing")
    op.create_index(
        "ix_api_billing_api_user_id", "api_billing", ["api_user_id"], unique=False
    )
    op.drop_column("api_billing", "user_id")
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

