"""adding date for vheicle model

Revision ID: 74a7ad99bd0c
Revises: 758da3d030eb
Create Date: 2025-07-22 11:12:32.735062

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74a7ad99bd0c"
down_revision = "758da3d030eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table_comment("api_pricing_plan", "", existing_comment=None, schema=None)
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_model",
        sa.Column(
            "commissioning_date",
            sa.DateTime(),
            nullable=True,
            comment="First time seen on the market",
        ),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "end_of_life_date",
            sa.DateTime(),
            nullable=True,
            comment="Last time seen on the market",
        ),
    )
    op.alter_column(
        "vehicle_model",
        "trendline_bib",
        existing_type=sa.BOOLEAN(),
        comment="If the trendline is based on SoH calculated by BIB",
        existing_nullable=True,
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_model",
        "trendline_bib",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="If the trendline is based on SoH calculated by BIB",
        existing_nullable=True,
    )
    op.drop_column("vehicle_model", "end_of_life_date")
    op.drop_column("vehicle_model", "commissioning_date")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.drop_table_comment("api_pricing_plan", existing_comment="", schema=None)
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

