"""change trendline

Revision ID: 758da3d030eb
Revises: 39cd6f83a8dd
Create Date: 2025-07-02 17:16:44.583776

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "758da3d030eb"
down_revision = "39cd6f83a8dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table_comment("api_pricing_plan", "", existing_comment=None, schema=None)
    op.create_table_comment("battery", "", existing_comment=None, schema=None)
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_model", sa.Column("trendline_bib", sa.Boolean(), nullable=True)
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    op.drop_column("vehicle_model", "trendline_version")
    op.drop_column("vehicle_model", "trendline_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model",
        sa.Column("trendline_model", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "trendline_version", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_column("vehicle_model", "trendline_bib")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table_comment("battery", existing_comment="", schema=None)
    op.drop_table_comment("api_pricing_plan", existing_comment="", schema=None)
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

