"""adding battery details

Revision ID: 7df6e9ff07f7
Revises: 9c45ec5712cf
Create Date: 2025-01-27 22:01:21.291485

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7df6e9ff07f7"
down_revision = "9c45ec5712cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battery",
        sa.Column("battery_name", sa.String(length=100), nullable=False),
        sa.Column("battery_oem", sa.String(length=100), nullable=True),
        sa.Column("battery_chemistry", sa.String(length=100), nullable=True),
        sa.Column("battery_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column("vehicle_model", sa.Column("battery_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "vehicle_model", "battery", ["battery_id"], ["id"])
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_constraint(None, "vehicle_model", type_="foreignkey")
    op.drop_column("vehicle_model", "battery_id")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table("battery")
    # ### end Alembic commands ###

