"""Ajout de la consommation attendue depuis EVDB

Revision ID: 9e26b9f878be
Revises: 4f6166e46805
Create Date: 2025-11-05 11:12:16.324051

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e26b9f878be"
down_revision = "4f6166e46805"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model", sa.Column("expected_consumption", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_model", "expected_consumption")
    # ### end Alembic commands ###
