"""add cycles

Revision ID: a06a9d609010
Revises: a5969306350f
Create Date: 2024-12-03 14:23:38.600786

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a06a9d609010"
down_revision = "a5969306350f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.alter_column("user", "role_id", existing_type=sa.UUID(), nullable=True)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.add_column(
        "vehicle_data",
        sa.Column("cycles", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.alter_column(
        "vehicle_model",
        "url_image",
        existing_type=sa.VARCHAR(length=400),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_model",
        "url_image",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=400),
        existing_nullable=True,
    )
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_column("vehicle_data", "cycles")
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.alter_column("user", "role_id", existing_type=sa.UUID(), nullable=False)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

