"""add required

Revision ID: a5969306350f
Revises: 6c12932e6c17
Create Date: 2024-11-27 17:05:26.147772

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5969306350f"
down_revision = "6c12932e6c17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_fleet WHERE role_id IS NULL")

    # Delete vehicle_data entries that have NULL vehicle_id
    op.execute("DELETE FROM vehicle_data WHERE vehicle_id IS NULL")

    # Delete vehicle_data entries that reference vehicles with any NULL required field
    op.execute("""
        DELETE FROM vehicle_data
        WHERE vehicle_id IN (
            SELECT id FROM vehicle
            WHERE fleet_id IS NULL
                OR region_id IS NULL
                OR vehicle_model_id IS NULL
        )
    """)

    # Now delete vehicles with any NULL required field
    op.execute(
        "DELETE FROM vehicle WHERE fleet_id IS NULL OR region_id IS NULL OR vehicle_model_id IS NULL"
    )
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.alter_column("fleet", "company_id", existing_type=sa.UUID(), nullable=False)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.alter_column(
        "fleet_aggregate", "fleet_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.alter_column(
        "regional_aggregate", "region_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.alter_column("user", "company_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user", "role_id", existing_type=sa.UUID(), nullable=False)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.alter_column("user_fleet", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user_fleet", "fleet_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user_fleet", "role_id", existing_type=sa.UUID(), nullable=False)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.alter_column("vehicle", "fleet_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("vehicle", "region_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "vehicle", "vehicle_model_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "vehicle_aggregate", "vehicle_model_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.alter_column(
        "vehicle_data", "vehicle_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_data", "vehicle_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_aggregate", "vehicle_model_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "vehicle", "vehicle_model_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("vehicle", "region_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("vehicle", "fleet_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.alter_column("user_fleet", "role_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("user_fleet", "fleet_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("user_fleet", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.alter_column("user", "role_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("user", "company_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.alter_column(
        "regional_aggregate", "region_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.alter_column(
        "fleet_aggregate", "fleet_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.alter_column("fleet", "company_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

