"""

Revision ID: b6afe1661155
Revises: f42bd9f77e7d
Create Date: 2025-01-08 16:09:49.265093

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6afe1661155"
down_revision = "f42bd9f77e7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("last_date_data", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "last_date_data")
    # ### end Alembic commands ###

