"""maj dev

Revision ID: e78f051b68c7
Revises: 54542c586857
Create Date: 2025-03-13 09:16:12.085436

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e78f051b68c7"
down_revision = "54542c586857"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tesla")
    op.create_table(
        "battery",
        sa.Column("battery_name", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("battery_chemistry", sa.String(length=100), nullable=True),
        sa.Column("battery_oem", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("net_capacity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table_comment("company", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("fleet_aggregate", "", existing_comment=None, schema=None)
    op.create_table_comment("make", "", existing_comment=None, schema=None)
    op.create_table_comment("oem", "", existing_comment=None, schema=None)
    op.create_table_comment("region", "", existing_comment=None, schema=None)
    op.create_table_comment(
        "regional_aggregate", "", existing_comment=None, schema=None
    )
    op.create_table_comment("role", "", existing_comment=None, schema=None)
    op.create_table_comment("user", "", existing_comment=None, schema=None)
    op.create_table_comment("user_fleet", "", existing_comment=None, schema=None)
    op.create_table_comment("vehicle_aggregate", "", existing_comment=None, schema=None)
    op.alter_column(
        "vehicle_data",
        "soh",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        type_=sa.Numeric(precision=5, scale=3),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_data",
        "consumption",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=5, scale=3),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_data",
        "soh_comparison",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=5, scale=3),
        existing_nullable=True,
    )
    op.create_table_comment("vehicle_data", "", existing_comment=None, schema=None)
    op.add_column("vehicle_model", sa.Column("battery_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "vehicle_model", "battery", ["battery_id"], ["id"])
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    op.drop_column("vehicle_model", "battery_oem")
    op.drop_column("vehicle_model", "battery_chemistry")
    op.drop_column("vehicle_model", "battery_name")
    op.drop_column("vehicle_model", "capacity")
    op.drop_column("vehicle_model", "net_capacity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_model",
        sa.Column(
            "net_capacity",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "capacity",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "battery_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "battery_chemistry",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "vehicle_model",
        sa.Column(
            "battery_oem", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_constraint(None, "vehicle_model", type_="foreignkey")
    op.drop_column("vehicle_model", "battery_id")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_data",
        "soh_comparison",
        existing_type=sa.Numeric(precision=5, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_data",
        "consumption",
        existing_type=sa.Numeric(precision=5, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "vehicle_data",
        "soh",
        existing_type=sa.Numeric(precision=5, scale=3),
        type_=sa.NUMERIC(precision=5, scale=2),
        existing_nullable=True,
    )
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("make", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.drop_table("battery")
    op.execute("DROP SCHEMA IF EXISTS tesla RESTRICT")
    # ### end Alembic commands ###

