"""wip

Revision ID: f2fd8d48b605
Revises:
Create Date: 2024-10-28 17:50:22.259546

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2fd8d48b605"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "region",
        sa.Column("region_name", sa.String(length=100), nullable=False),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle_model",
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("oem", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("net_capacity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("odometer_data", sa.Boolean(), nullable=True),
        sa.Column("soh_data", sa.Boolean(), nullable=True),
        sa.Column("soh_oem_data", sa.Boolean(), nullable=True),
        sa.Column("autonomy", sa.Integer(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fleet",
        sa.Column("fleet_name", sa.String(length=100), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "regional_aggregate",
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("avg_soh", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("avg_soc", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("avg_temperature", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("avg_voltage", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "energy_consumption", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("last_connection", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "vehicle_aggregate",
        sa.Column("vehicle_model_id", sa.UUID(), nullable=True),
        sa.Column("avg_soh", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "energy_consumption", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_fleet",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("fleet_id", sa.UUID(), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle",
        sa.Column("fleet_id", sa.UUID(), nullable=True),
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("vehicle_model_id", sa.UUID(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("licence_plate", sa.String(length=50), nullable=True),
        sa.Column("end_of_contract_date", sa.Date(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["fleet_id"],
            ["fleet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_model_id"],
            ["vehicle_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle_data",
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("odometer", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("speed", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("soh", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier of the row"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of the last update to this row",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Date of creation of this row",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_data")
    op.drop_table("vehicle")
    op.drop_table("user_fleet")
    op.drop_table("vehicle_aggregate")
    op.drop_table("user")
    op.drop_table("regional_aggregate")
    op.drop_table("fleet")
    op.drop_table("vehicle_model")
    op.drop_table("role")
    op.drop_table("region")
    op.drop_table("company")
    # ### end Alembic commands ###

