"""add models

Revision ID: f42bd9f77e7d
Revises: 64b59b6e2c6f
Create Date: 2024-12-17 16:48:04.701168

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f42bd9f77e7d"
down_revision = "64b59b6e2c6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "vehicle_model", sa.Column("version", sa.String(length=50), nullable=True)
    )
    op.create_table_comment("vehicle_model", "", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.drop_column("vehicle_model", "version")
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    op.create_table(
        "temp_table",
        sa.Column("vehicle_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "odometer",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("speed", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("location", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "soh", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("timestamp", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("cycles", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("consumption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("soh_comparison", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###

