"""change warranty_date

Revision ID: f48c15623d58
Revises: 100fc7089118
Create Date: 2024-12-10 10:41:17.094567

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f48c15623d58"
down_revision = "100fc7089118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add a temporary column with a different name
    op.add_column(
        "vehicle_model", sa.Column("warranty_date_temp", sa.Integer(), nullable=True)
    )

    # Update the temp column with calculated values from the OLD column
    op.execute("""
        UPDATE vehicle_model
        SET warranty_date_temp = (EXTRACT(YEAR FROM warranty_date)::INTEGER - 2024)
        WHERE warranty_date IS NOT NULL
    """)

    # Drop the old DATE column
    op.drop_column("vehicle_model", "warranty_date")

    # Rename the temp column to the final name
    op.alter_column(
        "vehicle_model",
        "warranty_date_temp",
        new_column_name="warranty_date",
        existing_type=sa.Integer(),
        existing_nullable=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("vehicle_model", existing_comment="", schema=None)
    op.alter_column(
        "vehicle_model",
        "warranty_date",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.drop_table_comment("vehicle_data", existing_comment="", schema=None)
    op.drop_table_comment("vehicle_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("user_fleet", existing_comment="", schema=None)
    op.drop_table_comment("user", existing_comment="", schema=None)
    op.drop_table_comment("role", existing_comment="", schema=None)
    op.drop_table_comment("regional_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("region", existing_comment="", schema=None)
    op.drop_table_comment("oem", existing_comment="", schema=None)
    op.drop_table_comment("fleet_aggregate", existing_comment="", schema=None)
    op.drop_table_comment("fleet", existing_comment="", schema=None)
    op.drop_table_comment("company", existing_comment="", schema=None)
    # ### end Alembic commands ###

