#!/bin/bash
set -e

# https://github.com/apache/iceberg/issues/11163

TEMPLATE="k8s/_templates/kc-oem-iceberg.tpl.yaml"
OUTPUT_DIR="k8s/kafka-connector/oems-iceberg"
OEMS=("bmw" "ford" "kia" "mercedes-benz" "renault" "stellantis" "tesla" "volkswagen" "volvo-cars")

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

for oem in "${OEMS[@]}"; do
  # Convert hyphen to underscore for namespace
  namespace=${oem//-/_}
  filepath="$OUTPUT_DIR/kc-${oem}-iceberg.yaml"

  # Use envsubst to replace variables
  export oem namespace
  echo "# Autogenerated from $TEMPLATE by $0" > "$filepath"
  envsubst < "$TEMPLATE" >> "$filepath"


  echo "✓ Generated $filepath"
done

echo ""
echo "Generated ${#OEMS[@]} connector configurations in $OUTPUT_DIR/"
